'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { FeedbackEditor } from './feedback-editor'
import { manualFeedback,type Feedback } from '@/lib/interviews/marking-validation'
import { reviewInterviewAction,retryInterviewAction,refundInterviewAction } from '@/lib/interviews/marking-actions'
export function AdminInterviewReview({id,format,initialFeedback,initialVersion,initialNotes,initialCorrections,terminal}:{id:string;format:'mmi'|'panel';initialFeedback:Feedback|null;initialVersion:number;initialNotes:string;initialCorrections:string;terminal:boolean}){
 const router=useRouter(),[feedback,setFeedback]=useState(initialFeedback??manualFeedback(format)),[version,setVersion]=useState(initialVersion),[notes,setNotes]=useState(initialNotes),[corrections,setCorrections]=useState(initialCorrections),[watched,setWatched]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[reason,setReason]=useState(''),[locked,setLocked]=useState(terminal)
 async function review(action:'start'|'save'|'approve',next=false){if(pending)return;setPending(true);try{const r=await reviewInterviewAction(id,version,action,feedback,notes,corrections,watched);if(r.ok){if(r.version)setVersion(r.version);setMessage(action==='approve'?'Feedback released.':'Draft saved.');if(action==='approve'){setLocked(true);if(next)router.push(r.nextId?`/admin/interviews/${r.nextId}`:'/admin/interviews')}}else setMessage(r.message??'Save failed.')}catch{setMessage('The save failed. Your edits are still here; try again.')}finally{setPending(false)}}
 async function retry(stage:'transcribe'|'assess'|'audit'){setPending(true);try{const r=await retryInterviewAction(id,stage);setMessage(r.message);if(r.ok)router.refresh()}catch{setMessage('Retry could not be queued.')}finally{setPending(false)}}
 async function refund(){setPending(true);try{const r=await refundInterviewAction(id,reason);setMessage(r.message);if(r.ok){setLocked(true);router.refresh()}}catch{setMessage('Refund could not be completed.')}finally{setPending(false)}}
 return <section className="space-y-6"><fieldset disabled={pending||locked} className="space-y-6 disabled:opacity-70"><div className="flex flex-wrap gap-3"><button className="rounded-full border px-4 py-3" onClick={()=>void review('start')}>Start review</button><button className="rounded-full border px-4 py-3" onClick={()=>{setFeedback(manualFeedback(format));setMessage('Manual feedback started. Fill in all relevant evidence and comments, then save.')}}>Mark manually / replace draft</button><button className="rounded-full border px-4 py-3" onClick={()=>void retry('transcribe')}>Retry transcription</button><button className="rounded-full border px-4 py-3" onClick={()=>void retry('assess')}>Retry AI assessment</button><button className="rounded-full border px-4 py-3" onClick={()=>void retry('audit')}>Retry evidence audit</button></div>
 <label className="block">Transcript correction notes (private; original transcript stays intact)<textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={5} value={corrections} onChange={e=>setCorrections(e.target.value)}/></label>
 <FeedbackEditor format={format} value={feedback} onChange={setFeedback}/>
 <label className="block">Private reviewer notes<textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <label className="flex items-start gap-3 rounded-2xl bg-surface-muted p-5"><input type="checkbox" className="mt-1" checked={watched} onChange={e=>setWatched(e.target.checked)}/><span>I have reviewed the complete recording, checked the transcript and evidence, and take responsibility for this final practice feedback.</span></label>
 <div className="flex flex-wrap gap-3"><button className="rounded-full border px-5 py-3" onClick={()=>void review('save')}>Save draft</button><button disabled={!watched} className="rounded-full bg-brand px-5 py-3 font-semibold text-brand-foreground disabled:opacity-50" onClick={()=>void review('approve')}>Approve and release</button><button disabled={!watched} className="rounded-full border px-5 py-3 disabled:opacity-50" onClick={()=>void review('approve',true)}>Approve and open next</button></div>
 <div className="border-t border-border pt-5"><label className="block">Reason this response cannot be graded<textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={2} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} className="mt-3 rounded-full border px-5 py-3 disabled:opacity-50" onClick={refund}>Mark ungradable and refund 1 credit</button></div></fieldset>
 {locked&&<p>This submission has been resolved and is locked.</p>}{message&&<p role="status" className="rounded-2xl border p-4">{message}</p>}{pending&&<p role="status">Saving…</p>}
 </section>
}
