'use client'
import { isMMIFeedback,manualMMIFeedback,type MMIFeedback,type MMIAudit } from '@/lib/interviews/mmi-feedback'
import type { MMISource } from '@/lib/interviews/mmi-evidence'
import type { MMIReportEntry } from '@/lib/interviews/mmi-summary'
import { MMITutorAssessment } from './mmi-tutor-assessment'
import { MMIStudentDraft } from './mmi-student-draft'
import { mmiReviewIssues } from '@/lib/interviews/mmi-review-readiness'
import { MMIReviewGuide } from './mmi-review-guide'
import { MMIConsolidatedSummary } from './mmi-feedback-view'
import { useState,type ReactNode } from 'react'
import { useRouter } from 'next/navigation'
import { FeedbackEditor } from './feedback-editor'
import { manualFeedback,type InterviewFeedbackData } from '@/lib/interviews/marking-validation'
import { classifyMMIResponseAction,reviewInterviewAction,retryInterviewAction,refundInterviewAction,startMMIAssessmentAction } from '@/lib/interviews/marking-actions'
import type { InterviewMarkingStatus,InterviewResponseDisposition } from '@/lib/supabase/types'
export function AdminInterviewReview({id,format,initialFeedback,initialVersion,initialNotes,initialCorrections,terminal,mmiSource,stationId,mockEntries,aiAssessment,audit,recording,illustrativeAssessment=false,transcriptionStatus,hasTranscript=false,responseDisposition,markingStatus}:{id:string;format:'mmi'|'panel';initialFeedback:InterviewFeedbackData|null;initialVersion:number;initialNotes:string;initialCorrections:string;terminal:boolean;mmiSource?:MMISource;stationId?:string;mockEntries?:MMIReportEntry[];aiAssessment?:MMIFeedback|null;audit?:MMIAudit|null;recording?:ReactNode;illustrativeAssessment?:boolean;transcriptionStatus?:string;hasTranscript?:boolean;responseDisposition?:InterviewResponseDisposition|null;markingStatus?:InterviewMarkingStatus|null}){
 const router=useRouter(),[feedback,setFeedback]=useState(initialFeedback??aiAssessment??(format==='mmi'&&mmiSource?manualMMIFeedback(stationId??id,mmiSource):manualFeedback(format))),[version,setVersion]=useState(initialVersion),[notes,setNotes]=useState(initialNotes),[corrections,setCorrections]=useState(initialCorrections),[watched,setWatched]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[reason,setReason]=useState(''),[locked,setLocked]=useState(terminal)
 const incomplete=isMMIFeedback(feedback)&&mmiReviewIssues(feedback).length>0
 async function review(action:'start'|'save'|'approve',destination:'next'|'dashboard'='next'){if(pending||locked)return;if(action==='approve'&&(!watched||incomplete)){setMessage('Complete the highlighted fields and confirm your recording review before approval.');return}setPending(true);try{const r=await reviewInterviewAction(id,version,action,feedback,notes,corrections,watched);if(r.ok){if(r.version)setVersion(r.version);setMessage(action==='approve'?'Feedback released.':'Draft saved.');if(action==='approve'){setLocked(true);router.push(destination==='dashboard'?'/admin':r.nextPath??'/admin/interviews')}}else setMessage(r.message??'Save failed.')}catch{setMessage('The save failed. Your edits are still here; try again.')}finally{setPending(false)}}
 async function retry(stage:'transcribe'|'assess'|'audit'){setPending(true);try{const r=await retryInterviewAction(id,stage);setMessage(r.message);if(r.ok)router.refresh()}catch{setMessage('Retry could not be queued.')}finally{setPending(false)}}
 async function classify(disposition:InterviewResponseDisposition){setPending(true);try{const r=await classifyMMIResponseAction(id,disposition);setMessage(r.message);if(r.ok)router.refresh()}catch{setMessage('The classification could not be saved.')}finally{setPending(false)}}
 async function startAI(){setPending(true);try{const r=await startMMIAssessmentAction(id);setMessage(r.message);if(r.ok)router.refresh()}catch{setMessage('AI marking could not be started.')}finally{setPending(false)}}
 async function refund(){setPending(true);try{const r=await refundInterviewAction(id,reason);setMessage(r.message);if(r.ok){setLocked(true);router.refresh()}}catch{setMessage('Refund could not be completed.')}finally{setPending(false)}}
 const emptyFailedMMI=format==='mmi'&&transcriptionStatus==='failed'&&!hasTranscript
 return <section className="space-y-8">{isMMIFeedback(feedback)&&<MMIReviewGuide value={feedback} audit={audit??null} watched={watched} locked={locked}/>} {emptyFailedMMI&&!aiAssessment&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-display text-xl font-semibold">No usable MMI transcript</h2>{responseDisposition?<><p className="mt-2">Tutor classification: <strong>{responseDisposition==='not_answered'?'Not answered':'Insubstantial response'}</strong>. This is based on your recording review and does not create candidate words.</p>{markingStatus==='needs_attention'?<button disabled={pending||locked} className="mt-4 rounded-full bg-brand px-5 py-3 font-semibold text-brand-foreground disabled:opacity-50" onClick={()=>void startAI()}>Start AI marking</button>:<p className="mt-3 text-sm font-semibold">AI marking is queued or processing.</p>}</>:<><p className="mt-2">Listen to the complete recording, then choose the accurate outcome. The AI will only run after you explicitly start it.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={pending||locked} className="rounded-full border border-amber-500 bg-white px-4 py-3 disabled:opacity-50" onClick={()=>void classify('insubstantial')}>Mark as insubstantial</button><button disabled={pending||locked} className="rounded-full border border-amber-500 bg-white px-4 py-3 disabled:opacity-50" onClick={()=>void classify('not_answered')}>Mark as not answered</button></div></>}</section>}{format==='mmi'&&mmiSource&&<MMITutorAssessment illustrative={illustrativeAssessment} recording={recording} source={mmiSource} assessment={aiAssessment??null} audit={audit??null}/>}<fieldset disabled={pending||locked} className="space-y-6 disabled:opacity-70"><details className="rounded-2xl border border-border p-4"><summary className="cursor-pointer text-sm font-semibold">Review tools and processing</summary><div className="mt-3 flex flex-wrap gap-3"><button className="rounded-full border px-4 py-3" onClick={()=>void review('start')}>Start review</button><button className="rounded-full border px-4 py-3" onClick={()=>{setFeedback(format==='mmi'&&mmiSource?manualMMIFeedback(stationId??id,mmiSource):manualFeedback(format));setMessage('Manual feedback started. Fill in all relevant evidence and comments, then save.')}}>Mark manually / replace draft</button><button className="rounded-full border px-4 py-3" onClick={()=>void retry('transcribe')}>Retry transcription</button>{(!emptyFailedMMI||!!aiAssessment)&&<button className="rounded-full border px-4 py-3" onClick={()=>void retry('assess')}>Retry AI assessment</button>}{(!emptyFailedMMI||!!aiAssessment)&&<button className="rounded-full border px-4 py-3" onClick={()=>void retry('audit')}>Retry evidence audit</button>}</div></details>
 <details className="rounded-2xl border border-border p-4"><summary className="cursor-pointer text-sm font-semibold">Private transcript correction notes</summary><label className="mt-3 block">Transcript correction notes (private; original transcript stays intact)<textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={5} value={corrections} onChange={e=>setCorrections(e.target.value)}/></label></details>
 {isMMIFeedback(feedback)?<MMIStudentDraft value={feedback} onChange={setFeedback}/>:<FeedbackEditor format={format} value={feedback} onChange={setFeedback}/>}
 {isMMIFeedback(feedback)&&mockEntries&&<details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Preview consolidated full-mock summary</summary><p className="mt-3 text-sm text-muted">Includes this unsaved draft for preview; students only see approved station feedback.</p><MMIConsolidatedSummary entries={mockEntries.map(e=>e.id===id?{...e,status:'released',feedback}:e)} total={8}/></details>}
 <label className="block">Private reviewer notes<span className="ml-2 text-xs text-muted">Optional · tutor only</span><textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <div id="mmi-release-review" tabIndex={-1} className="scroll-mt-6 space-y-3"><h3 className="font-semibold">Final review &amp; release</h3><p className="text-sm text-muted">{isMMIFeedback(feedback)?'Check the student preview above. Approval sends the report to the student; private notes stay private.':'Check the feedback before approval. Private notes stay private.'}</p><label className="flex items-start gap-3 rounded-2xl bg-surface-muted p-5"><input type="checkbox" className="mt-1" checked={watched} onChange={e=>setWatched(e.target.checked)}/><span>I have reviewed the complete recording, checked the transcript and evidence, and take responsibility for this final practice feedback.</span></label></div>
 {incomplete&&<p className="text-sm text-amber-900">Complete the items in “Needs completing” before approval. You can save an unfinished draft.</p>}<div className="flex flex-wrap gap-3"><button className="rounded-full border px-5 py-3" onClick={()=>void review('save')}>Save draft</button><button disabled={!watched||incomplete} className="rounded-full bg-brand px-5 py-3 font-semibold text-brand-foreground disabled:opacity-50" onClick={()=>void review('approve','next')}>Approve &amp; open next marking</button><button disabled={!watched||incomplete} className="rounded-full border px-5 py-3 disabled:opacity-50" onClick={()=>void review('approve','dashboard')}>Approve &amp; return to admin dashboard</button></div>
 <div className="border-t border-border pt-5"><label className="block">Reason this response cannot be graded<textarea className="mt-2 w-full rounded-xl border border-border p-3" rows={2} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} className="mt-3 rounded-full border px-5 py-3 disabled:opacity-50" onClick={refund}>Mark ungradable and refund marking credits</button></div></fieldset>
 {locked&&<p>This submission has been resolved and is locked.</p>}{message&&<p role="status" className="rounded-2xl border p-4">{message}</p>}{pending&&<p role="status">Saving…</p>}
 </section>
}
