'use client'
import type { Feedback } from '@/lib/interviews/marking-validation'
import { DOMAIN_LABELS,PART_A_DOMAINS,PART_B_DOMAINS,PANEL_DOMAINS,PERFORMANCE_BANDS } from '@/lib/interviews/marking-rubric'
const input='mt-1 w-full rounded-lg border border-border bg-background p-3'
export function FeedbackEditor({value,onChange,format}:{value:Feedback;format:'mmi'|'panel';onChange:(v:Feedback)=>void}){
 function domain(index:number,patch:Partial<Feedback['domains'][number]>){onChange({...value,domains:value.domains.map((d,i)=>i===index?{...d,...patch}:d)})}
 return <section className="space-y-5" aria-label="Editable final feedback"><h2 className="font-display text-2xl font-semibold">Final feedback</h2><p className="text-sm text-muted">Edit every field. Only this structured feedback is copied to the student on approval.</p>
 <div className="grid gap-4 sm:grid-cols-2"><label>Overall score<input type="number" min={1} max={7} step={.5} value={value.overall.score} className={input} onChange={e=>onChange({...value,overall:{...value.overall,score:Number(e.target.value)}})}/></label><label>Practice band<select className={input} value={value.overall.band} onChange={e=>onChange({...value,overall:{...value.overall,band:e.target.value}})}>{PERFORMANCE_BANDS.map(b=><option key={b}>{b}</option>)}</select></label></div>
 <label className="block">Overall summary<textarea className={input} rows={4} value={value.overall.summary} onChange={e=>onChange({...value,overall:{...value.overall,summary:e.target.value}})}/></label>
 {value.domains.map((d,i)=><fieldset key={d.key} className="space-y-3 rounded-2xl border border-border p-4"><legend className="px-2 font-semibold">{d.label}</legend><label className="block">Domain label<input className={input} value={d.label} onChange={e=>domain(i,{label:e.target.value})}/></label><label className="flex items-center gap-3"><input type="checkbox" checked={d.applicable} onChange={e=>domain(i,{applicable:e.target.checked,score:e.target.checked?4:null})}/>Applicable and supported by evidence</label>{d.applicable&&<label className="block">Score<input type="number" min={1} max={7} step={.5} value={d.score??4} className={input} onChange={e=>domain(i,{score:Number(e.target.value)})}/></label>}<label className="block">Evidence (one observation per line)<textarea className={input} rows={3} value={d.evidence.join('\n')} onChange={e=>domain(i,{evidence:e.target.value.split('\n')})}/></label><label className="block">Comment or reason not applicable<textarea className={input} rows={2} value={d.comment} onChange={e=>domain(i,{comment:e.target.value})}/></label><button className="rounded-full border px-4 py-2 text-sm" onClick={()=>onChange({...value,domains:value.domains.filter((_,n)=>n!==i)})}>Remove domain</button></fieldset>)}
 <label className="block">Add a relevant domain<select className={input} value="" onChange={e=>{if(e.target.value)onChange({...value,domains:[...value.domains,{key:e.target.value,label:DOMAIN_LABELS[e.target.value],applicable:false,score:null,evidence:[],comment:''}]})}}><option value="">Choose domain</option>{Object.entries(DOMAIN_LABELS).filter(([key])=>key in (format==='panel'?PANEL_DOMAINS:{...PART_A_DOMAINS,...PART_B_DOMAINS})).filter(([key])=>!value.domains.some(d=>d.key===key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <TextList label="Strengths" values={value.strengths} onChange={strengths=>onChange({...value,strengths})}/><TextList label="Priority improvements" values={value.priorities} onChange={priorities=>onChange({...value,priorities})}/><label className="block">One specific next-practice task<textarea className={input} rows={3} value={value.practice_task} onChange={e=>onChange({...value,practice_task:e.target.value})}/></label>
 </section>
}
function TextList({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){return <label className="block">{label} (one per line)<textarea className={input} rows={3} value={values.join('\n')} onChange={e=>onChange(e.target.value.split('\n'))}/></label>}
