'use client'
import { useState } from 'react'
import { MMI_DOMAINS,type MMIDomainKey } from '@/lib/interviews/mmi-rubric-v2'
import { mmiBand,mmiReferences,type MMIFeedback,type MMIEvidence,type MMIHighlight } from '@/lib/interviews/mmi-feedback'
import { setMMIDomainRating } from '@/lib/interviews/mmi-editor-state'
import { mmiClosing } from '@/lib/interviews/mmi-summary'
const input='mt-1 w-full rounded-lg border border-border bg-background p-3'
const button='rounded-full border border-border px-4 py-2 text-sm hover:bg-brand-muted'
function Text({label,value,onChange,rows=3}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}){return <label className="block text-sm">{label}<textarea className={input} rows={rows} value={value} onChange={e=>onChange(e.target.value)}/></label>}
const refList=(text:string)=>text.split(',').map(t=>t.trim()).filter(Boolean)
function EvidenceEditor({value,onChange,max=2}:{value:MMIEvidence[];onChange:(v:MMIEvidence[])=>void;max?:number}){
 return <div className="space-y-3">{value.map((e,i)=><fieldset key={i} className="space-y-3 rounded-xl border border-border p-4"><legend className="text-sm">Evidence {i+1}</legend><div className="grid gap-3 sm:grid-cols-2"><label>Type<select className={input} value={e.kind} onChange={event=>onChange(value.map((v,n)=>n===i?{...v,kind:event.target.value as MMIEvidence['kind']}:v))}><option value="quote">Exact quotation</option><option value="paraphrase">Labelled paraphrase</option><option value="omission">Elicited omission</option></select></label><label>Speaker<select className={input} value={e.speaker} onChange={event=>onChange(value.map((v,n)=>n===i?{...v,speaker:event.target.value as MMIEvidence['speaker']}:v))}>{['candidate','interviewer','actor','recording_note','unknown','prompt'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label></div><Text label="Evidence text (no quotation marks around paraphrases)" value={e.text} onChange={text=>onChange(value.map((v,n)=>n===i?{...v,text}:v))}/><label className="block text-sm">Reference labels, separated by commas<input className={input} value={e.references.join(', ')} onChange={event=>onChange(value.map((v,n)=>n===i?{...v,references:refList(event.target.value)}:v))}/></label><button type="button" className={button} onClick={()=>onChange(value.filter((_,n)=>n!==i))}>Remove evidence</button></fieldset>)}{value.length<max&&<button type="button" className={button} onClick={()=>onChange([...value,{kind:'paraphrase',speaker:'candidate',text:'',references:[]}])}>Add evidence reference</button>}</div>
}
function Highlights({label,value,domains,onChange}:{label:string;value:MMIHighlight[];domains:MMIDomainKey[];onChange:(v:MMIHighlight[])=>void}){
 return <section className="space-y-3"><h3 className="font-semibold">{label}</h3>{value.map((h,i)=><div key={i} className="space-y-2 rounded-xl border border-border p-4"><label>Domain<select className={input} value={h.domain} onChange={e=>onChange(value.map((v,n)=>n===i?{...v,domain:e.target.value as MMIDomainKey}:v))}>{Object.entries(MMI_DOMAINS).map(([key,d])=><option key={key} value={key}>{d.label}</option>)}</select></label><Text label="Specific observation / improvement" value={h.text} onChange={text=>onChange(value.map((v,n)=>n===i?{...v,text}:v))}/><label>Evidence references<input className={input} value={h.references.join(', ')} onChange={e=>onChange(value.map((v,n)=>n===i?{...v,references:refList(e.target.value)}:v))}/></label><button className={button} type="button" onClick={()=>onChange(value.filter((_,n)=>n!==i))}>Remove item</button></div>)}{value.length<5&&domains.length>0&&<button className={button} type="button" onClick={()=>onChange([...value,{domain:domains[0],text:'',references:[]}])}>Add item</button>}</section>
}
function ReviewerEvidence({value,onChange}:{value:MMIFeedback;onChange:(v:MMIFeedback)=>void}){
 const scope=value.reviewer_scope
 return <details className="space-y-3 rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Add evidence from your own recording review</summary><p className="mt-3 text-sm text-muted">Use this for directly checked observations or transcript corrections, including manual marking when transcription failed. These R-labelled references are attributed to you. The original transcript stays intact.</p>
 <label className="block">Media you actually inspected<select className={input} value={scope.media_inspected} onChange={e=>onChange({...value,reviewer_scope:{...scope,media_inspected:e.target.value as typeof scope.media_inspected}})}>{['none','audio','video'].map(s=><option key={s}>{s}</option>)}</select></label>
 <label className="block">Recording completeness<select className={input} value={scope.completeness} onChange={e=>onChange({...value,reviewer_scope:{...scope,completeness:e.target.value as typeof scope.completeness}})}>{['unknown','partial','complete'].map(s=><option key={s}>{s}</option>)}</select></label>
 <label className="block">Primary-task coverage in what you inspected<select className={input} value={scope.primary_task_coverage} onChange={e=>onChange({...value,reviewer_scope:{...scope,primary_task_coverage:e.target.value as typeof scope.primary_task_coverage}})}>{['unknown','excerpt','full'].map(s=><option key={s}>{s}</option>)}</select></label>
 {value.reviewer_evidence.map((r,i)=>{const change=(patch:Partial<typeof r>)=>onChange({...value,reviewer_evidence:value.reviewer_evidence.map((v,n)=>n===i?{...v,...patch}:v)});return <fieldset key={r.id} className="mt-4 space-y-3 rounded-xl border border-border p-4"><legend className="text-xs">Reference {r.id}</legend><label>Type<select className={input} value={r.kind} onChange={e=>change({kind:e.target.value as typeof r.kind})}><option value="observation">Reviewer observation (not a verbatim quote)</option><option value="transcript_correction">Exact speech checked against recording</option></select></label><label>Speaker<select className={input} value={r.speaker} onChange={e=>change({speaker:e.target.value as typeof r.speaker})}>{['candidate','interviewer','actor','recording_note','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><Text label="Observed evidence / checked exact speech" value={r.text} onChange={text=>change({text})}/><label>Timestamp if checked (m:ss, otherwise leave blank)<input className={input} value={r.timestamp??''} onChange={e=>change({timestamp:e.target.value||null})}/></label><p className="text-sm">Source: reviewer-inspected {r.media}</p><button type="button" className={button} onClick={()=>onChange({...value,reviewer_evidence:value.reviewer_evidence.filter((_,n)=>n!==i)})}>Remove reviewer evidence</button></fieldset>})}
 {scope.media_inspected!=='none'&&value.reviewer_evidence.length<50&&<button type="button" className={button} onClick={()=>onChange({...value,reviewer_evidence:[...value.reviewer_evidence,{id:`R${Array.from({length:51},(_,i)=>i+1).find(n=>!value.reviewer_evidence.some(r=>r.id===`R${n}`))}`,speaker:'candidate',text:'',timestamp:null,media:scope.media_inspected as 'audio'|'video',kind:'observation'}]})}>Add checked recording evidence</button>}
 </details>
}
export function MMIFeedbackEditor({value,onChange}:{value:MMIFeedback;onChange:(v:MMIFeedback)=>void}){
 const [locked,setLocked]=useState(true)
 const domain=(index:number,patch:Partial<MMIFeedback['domains'][number]>)=>onChange({...value,domains:value.domains.map((d,i)=>i===index?{...d,...patch}:d)})
 const spec=(patch:Partial<MMIFeedback['specification']>)=>onChange({...value,specification:{...value.specification,...patch}})
 const selected=value.specification.primary_domains.map(d=>d.key),scored=value.domains.filter(d=>d.status==='scored').map(d=>d.key)
 function revise(){setLocked(false);onChange({...value,domains:value.domains.map(d=>({...d,status:selected.includes(d.key)?'insufficient_evidence':'not_applicable',score:null,evidence:[],rationale:'',improvement:'',needed_evidence:''})),global:{status:'insufficient_evidence',score:null,reason:''},strengths:[],priorities:[],closing:{verdict:'',successful_improvement:''}})}
 return <section className="space-y-6" aria-label="Editable MMI feedback v2"><h2 className="font-display text-2xl font-semibold">Final feedback</h2><p className="text-sm text-muted">MMI rubric v2 · integer 1–7 scores · unscored is not a low score. No practice exercises. Only approved feedback reaches the student.</p>
 <details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Source references and evidence limits</summary><p className="mt-3 text-sm">Automatic assessment used transcript only. Completeness: {value.source.completeness}; task coverage: {value.source.primary_task_coverage}.</p>{value.source.limitations.map((t,i)=><p className="mt-2 text-sm text-muted" key={i}>{t}</p>)}{mmiReferences(value).map(r=><p key={r.id} className="mt-3 whitespace-pre-wrap text-sm"><strong>{r.id} · {r.speaker}{r.timestamp?` · ${r.timestamp}`:''}</strong>{r.label_origin==='added'?' (added label)':''}: {r.text}</p>)}</details>
 <section className="space-y-3 rounded-2xl border border-border p-5"><h3 className="font-semibold">Station expectations — establish before scoring</h3><p className="text-sm">Revising expectations clears scores and coaching text so the station can be reassessed against the revised task.</p>{locked?<><p>{value.specification.task}</p><button className={button} type="button" onClick={revise}>Revise station expectations</button></>:<><Text label="Task" value={value.specification.task} onChange={task=>spec({task})}/><Text label="Candidate role" value={value.specification.role} onChange={role=>spec({role})}/><label>Assessment basis<select className={input} value={value.specification.basis} onChange={e=>spec({basis:e.target.value as MMIFeedback['specification']['basis']})}>{['supplied','provisional','inferred'].map(t=><option key={t}>{t}</option>)}</select></label>{(['essential_expectations','optional_enrichment','acceptable_approaches','limitations'] as const).map(field=><Text key={field} label={field.replaceAll('_',' ')+' (one per line)'} value={value.specification[field].join('\n')} onChange={text=>spec({[field]:text.split('\n').filter(Boolean)})}/>)}<Text label="Interaction conditions / timing known" value={value.specification.interaction_conditions} onChange={interaction_conditions=>spec({interaction_conditions})}/>{Object.entries(MMI_DOMAINS).map(([key,d])=><div key={key}><label className="flex gap-2"><input type="checkbox" checked={selected.includes(key as MMIDomainKey)} onChange={e=>{const k=key as MMIDomainKey;onChange({...value,specification:{...value.specification,primary_domains:e.target.checked?[...value.specification.primary_domains,{key:k,reason:''}]:value.specification.primary_domains.filter(x=>x.key!==k)},domains:[...value.domains.filter(x=>x.key!==k),{key:k,status:e.target.checked?'insufficient_evidence':'not_applicable',score:null,evidence:[],rationale:e.target.checked?'':'Not elicited by this station.',improvement:'',needed_evidence:''}]})}}/>{d.label}</label>{selected.includes(key as MMIDomainKey)&&<Text label="Task-based reason for selecting this domain" value={value.specification.primary_domains.find(x=>x.key===key)!.reason} onChange={reason=>spec({primary_domains:value.specification.primary_domains.map(x=>x.key===key?{...x,reason}:x)})}/>}</div>)}<button className={button} type="button" disabled={!selected.length||value.specification.primary_domains.some(d=>!d.reason.trim())} onClick={()=>setLocked(true)}>Lock expectations and assess</button></>}</section>
 <ReviewerEvidence value={value} onChange={onChange}/>
 <fieldset disabled={!locked} className="space-y-6 disabled:opacity-50">{value.domains.map((d,i)=><section className="space-y-4 rounded-2xl border border-border p-5" key={d.key}><h3 className="font-semibold">{MMI_DOMAINS[d.key].label}</h3><label>Status<select className={input} value={d.status} onChange={e=>{const status=e.target.value as typeof d.status;if(status!=='not_applicable')onChange(setMMIDomainRating(value,d.key,status==='scored'?4:null))}}>{selected.includes(d.key)?<><option value="insufficient_evidence">Unscored — insufficient evidence</option><option value="scored">Scored</option></>:<option value="not_applicable">Not applicable — not elicited</option>}</select></label>{d.status==='scored'&&<><label>Integer score<input className={input} type="number" min={1} max={7} step={1} value={d.score??''} onChange={e=>domain(i,{score:e.target.value===''?null:Number(e.target.value)})}/></label><p className="text-sm text-muted">{d.score&&Number.isInteger(d.score)&&d.score>=1&&d.score<=7?`${mmiBand(d.score)}: ${MMI_DOMAINS[d.key].anchors[String(d.score) as '1']}`:'Select an integer score.'}</p></>}<EvidenceEditor value={d.evidence} onChange={evidence=>domain(i,{evidence})}/><Text label={d.status==='scored'?'Why this anchor / adjacent-band distinction':'Basis / evidence limitation'} value={d.rationale} onChange={rationale=>domain(i,{rationale})}/>{d.status==='scored'?<Text label={d.score===7?'What to maintain or extend':'Specific next-band improvement (no exercise)'} value={d.improvement} onChange={improvement=>domain(i,{improvement})}/>:d.status==='insufficient_evidence'?<Text label="Material needed to assess" value={d.needed_evidence} onChange={needed_evidence=>domain(i,{needed_evidence})}/>:null}</section>)}
 <section className="space-y-3"><h3 className="font-semibold">Global rating for consolidated summary</h3><p className="text-sm text-muted">Judge the primary task holistically. Do not average domain scores or score an isolated excerpt.</p><label>Global rating<select className={input} value={value.global.score??''} onChange={e=>onChange({...value,global:{...value.global,status:e.target.value?'scored':'insufficient_evidence',score:e.target.value?Number(e.target.value):null}})}><option value="">Unscored — insufficient evidence</option>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} · {mmiBand(n)}</option>)}</select></label><Text label="Decisive reason / limitation (include why a partial station is assessable, if applicable)" value={value.global.reason} onChange={reason=>onChange({...value,global:{...value.global,reason}})}/></section>
 <Highlights label="What worked well" value={value.strengths} domains={scored} onChange={strengths=>onChange({...value,strengths})}/><Highlights label="What to work on" value={value.priorities} domains={scored} onChange={priorities=>onChange({...value,priorities})}/>
 <section className="space-y-3"><h3 className="font-semibold">Supported concerns / clarification</h3>{value.concerns.map((c,i)=>{const change=(patch:Partial<typeof c>)=>onChange({...value,concerns:value.concerns.map((v,n)=>n===i?{...v,...patch}:v)});return <fieldset key={c.id} className="space-y-3 rounded-xl border border-border p-4"><label>Status<select className={input} value={c.status} onChange={e=>change({status:e.target.value as typeof c.status})}>{['clarification_needed','observed_concern','serious_observed_concern'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Evidence certainty<select className={input} value={c.certainty} onChange={e=>change({certainty:e.target.value as typeof c.certainty})}><option value="uncertain">Uncertain</option><option value="clear">Clear</option></select></label><Text label="Supported conduct / ambiguity, not a character judgement" value={c.description} onChange={description=>change({description})}/><Text label="Consequence / significance" value={c.consequence} onChange={consequence=>change({consequence})}/><Text label="Repair, clarification and context" value={c.repair} onChange={repair=>change({repair})}/><EvidenceEditor max={3} value={c.evidence} onChange={evidence=>change({evidence})}/><button className={button} type="button" onClick={()=>onChange({...value,concerns:value.concerns.filter((_,n)=>n!==i)})}>Remove concern</button></fieldset>})}<button className={button} type="button" onClick={()=>onChange({...value,concerns:[...value.concerns,{id:crypto.randomUUID(),status:'clarification_needed',description:'',consequence:'',certainty:'uncertain',repair:'',evidence:[]}]})}>Add concern / clarification</button></section>
 <section className="space-y-3"><h3 className="font-semibold">One closing paragraph</h3><Text label="Concise performance verdict" value={value.closing.verdict} onChange={verdict=>onChange({...value,closing:{...value.closing,verdict}})}/><Text label="What successful improvement would look like (or the evidence limitation)" value={value.closing.successful_improvement} onChange={successful_improvement=>onChange({...value,closing:{...value.closing,successful_improvement}})}/><p className="text-sm text-muted">Supported concerns are included automatically, with their status and station reference.</p><p className="rounded-xl bg-surface-muted p-4 leading-7">{mmiClosing(value)}</p></section>
 </fieldset></section>
}
