import { MMI_DOMAINS } from '@/lib/interviews/mmi-rubric-v2'
import { mmiBand,mmiReferences,type MMIFeedback,type MMIEvidence } from '@/lib/interviews/mmi-feedback'
import { aggregateMMI,mmiClosing,type MMIReportEntry } from '@/lib/interviews/mmi-summary'
export function MMIEvidenceView({evidence,feedback}:{evidence:MMIEvidence;feedback:MMIFeedback}){
 return <div className="text-sm leading-6"><p>{evidence.kind==='quote'?`“${evidence.text}”`:`${evidence.kind==='omission'?'Omission':'Paraphrase'}: ${evidence.text}`} <span className="text-muted">({evidence.speaker.replaceAll('_',' ')}; {evidence.references.join(', ')})</span></p><details className="mt-1"><summary className="cursor-pointer text-brand">Source evidence</summary>{evidence.references.map(id=>{const r=mmiReferences(feedback).find(r=>r.id===id);return r?<p key={id} className="mt-2 whitespace-pre-wrap"><strong>{r.id} · {r.id.startsWith('R')?'Reviewer-supplied ':''}{r.speaker.replaceAll('_',' ')}{r.timestamp?` · ${r.timestamp}`:''}</strong>{r.label_origin==='added'?' (added reference label)':''}: {r.text}</p>:null})}</details></div>
}
export function MMIStationFeedback({feedback}:{feedback:MMIFeedback}){
 const s=feedback.specification
 return <section className="space-y-5" aria-label="MMI station analysis"><p className="text-sm text-muted">EMeducate 1–7 coaching rubric v2 · Human calibration pending · Not an admissions prediction</p>
 <details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Task and assessment basis</summary><p className="mt-2">{s.task}</p><p className="mt-2 text-sm">Role: {s.role} · {s.basis} specification</p><p className="mt-2 text-sm">{s.interaction_conditions}</p><h4 className="mt-4 font-semibold">Essential expectations</h4><ul className="mt-2 list-disc space-y-1 pl-5">{s.essential_expectations.map((t,i)=><li key={i}>{t}</li>)}</ul><details className="mt-3"><summary className="cursor-pointer text-brand">Selected domains and evidence limits</summary><ul className="mt-2 space-y-2">{s.primary_domains.map(d=><li key={d.key}><strong>{MMI_DOMAINS[d.key].label}:</strong> {d.reason}</li>)}{[...s.limitations,...feedback.source.limitations].map((t,i)=><li key={i} className="text-sm text-muted">{t}</li>)}</ul><p className="mt-3 text-sm">Media assessed automatically: transcript · Completeness: {feedback.source.completeness} · Task coverage: {feedback.source.primary_task_coverage}</p>{feedback.reviewer_evidence.length>0&&<p className="mt-2 text-sm">Reviewer inspected: {feedback.reviewer_scope.media_inspected} · {feedback.reviewer_scope.completeness}. Reviewer observations/corrections have R-prefixed references; they do not change the original transcript.</p>}</details></details>
 {feedback.domains.map(d=><article key={d.key} className="space-y-3 rounded-2xl border border-border p-5"><h3 className="font-semibold">{MMI_DOMAINS[d.key].label}</h3><p className="font-semibold text-brand">{d.status==='scored'?`${d.score}/7 · ${mmiBand(d.score!)}`:d.status==='not_applicable'?'Not applicable — not elicited':'Unscored — insufficient evidence'}</p>{d.evidence.map((e,i)=><MMIEvidenceView key={i} evidence={e} feedback={feedback}/>)}<p className="text-sm leading-7"><strong>{d.status==='scored'?'Why':'Basis'}:</strong> {d.rationale}</p>{d.status==='scored'?<p className="text-sm leading-7"><strong>{d.score===7?'Maintain / extend':'To improve'}:</strong> {d.improvement}</p>:d.status==='insufficient_evidence'?<p className="text-sm leading-7"><strong>Needed to assess:</strong> {d.needed_evidence}</p>:null}</article>)}
 {feedback.concerns.length>0&&<details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Evidence for supported concerns / clarification</summary>{feedback.concerns.map(c=><div key={c.id} className="mt-4 space-y-2"><p><strong>{c.status.replaceAll('_',' ')}:</strong> {c.description}</p><p>{c.consequence}</p><p className="text-sm">Evidence certainty: {c.certainty}. {c.repair}</p>{c.evidence.map((e,i)=><MMIEvidenceView key={i} evidence={e} feedback={feedback}/>)}</div>)}</details>}
 </section>
}
/** The student sees the approved coaching summary, without the assessor's working notes. */
export function MMIStudentFeedback({feedback,approved=true,stationLabel}:{feedback:MMIFeedback;approved?:boolean;stationLabel?:string}){
 const assessed=feedback.domains.filter(d=>d.status!=='not_applicable')
 return <section className="space-y-6" aria-label="Student station feedback">
  <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-brand-muted p-6"><div><h2 className="font-display text-2xl font-semibold">Your feedback</h2><p className="mt-1 text-sm text-muted">{approved?'Reviewed by your EMeducate tutor':'Draft feedback · awaiting tutor review'}</p></div><div className="text-right"><p className="text-3xl font-semibold tabular-nums text-brand">{feedback.global.score===null?'Unscored':`${feedback.global.score} / 7`}</p><p className="mt-1 text-sm">{feedback.global.score===null?'Insufficient evidence':mmiBand(feedback.global.score)}</p></div></div>
  {feedback.global.score===null&&<p className="text-sm text-muted">{feedback.global.reason}</p>}
  <section><h3 className="font-semibold">Domains assessed</h3><dl className="mt-3 divide-y divide-border rounded-2xl border border-border px-5">{assessed.map(d=><div className="flex items-start justify-between gap-5 py-4" key={d.key}><dt className="text-sm">{MMI_DOMAINS[d.key].label}{d.status==='insufficient_evidence'&&<p className="mt-1 text-xs text-muted">{d.needed_evidence}</p>}</dt><dd className="shrink-0 text-sm font-semibold tabular-nums">{d.score===null?'Unscored':`${d.score} / 7`}</dd></div>)}</dl></section>
  <div className="grid gap-6 sm:grid-cols-2">{[["What you did well",feedback.strengths],["What to improve",feedback.priorities]].map(([title,items])=>{const points=items as MMIFeedback['strengths'];return points.length>0?<section key={title as string}><h3 className="font-semibold">{title as string}</h3><ul className="mt-3 list-disc space-y-3 pl-5 text-sm leading-7">{points.map((p,i)=><li key={i}>{p.text}</li>)}</ul></section>:null})}</div>
  <section className="rounded-2xl bg-surface-muted p-5"><h3 className="font-semibold">Overall feedback</h3><p className="mt-2 leading-7">{mmiClosing(feedback,stationLabel)}</p></section>
 </section>
}
export function MMIConsolidatedSummary({entries,total}:{entries:MMIReportEntry[];total?:number}){
 const s=aggregateMMI(entries,total)
 return <section className="mt-8 space-y-5 border-t border-border pt-7" aria-label="Consolidated MMI summary"><h2 className="font-display text-2xl font-semibold">Circuit feedback</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Station</th><th className="p-3">Global rating</th></tr></thead><tbody>{s.stations.map(station=><tr key={station.id} className="border-t border-border"><td className="p-3">{station.index+1}. {station.title}</td><td className="p-3">{station.score===null?'Unscored':`${station.score}/7 · ${mmiBand(station.score)}`}</td></tr>)}</tbody></table></div><p className="font-semibold">{s.display===null?'No average':s.scorable===1?`Single scorable-station result: ${s.display}/7 · ${s.band}`:`Overall circuit score: ${s.display}/7 · ${s.band}`}</p><p className="text-sm text-muted">Coverage: {s.scorable} of {s.total} stations. {s.scorable===1?'Single-station result, not a circuit estimate. ':''}Only reviewed scores from this rubric are included. {s.roundingBoundary?'The band uses the unrounded mean. ':''}This is a coaching summary, not an admissions prediction.</p>
 {s.strengths.length>0&&<div><h3 className="font-semibold">What worked well</h3><ul className="mt-2 list-disc space-y-2 pl-5">{s.strengths.map((h,i)=><li key={i}>{h.text} <span className="text-sm text-muted">(Station {h.sources.map(source=>source.station).join(', ')})</span></li>)}</ul></div>}
 {s.priorities.length>0&&<div><h3 className="font-semibold">What to work on</h3><ul className="mt-2 list-disc space-y-2 pl-5">{s.priorities.map((h,i)=><li key={i}>{h.text} <span className="text-sm text-muted">(Station {h.sources.map(source=>source.station).join(', ')})</span></li>)}</ul></div>}
 <p className="rounded-2xl bg-surface-muted p-5 leading-7">{s.closing}</p></section>
}
export function MMIFullMockFeedback({entries,total=8}:{entries:MMIReportEntry[];total?:number}){
 const report=aggregateMMI(entries,total)
 return <section className="mt-8 space-y-5" aria-label="Full MMI report"><h2 className="font-display text-2xl font-semibold">Full MMI feedback</h2>{report.stations.map(s=><details key={s.id} className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Station {s.index+1} · {s.title}</summary><div className="mt-5">{s.feedback?<MMIStudentFeedback feedback={s.feedback} stationLabel={`Station ${s.index+1}`}/>:<p>{s.reason} Open the original response to view any earlier feedback.</p>}</div></details>)}<MMIConsolidatedSummary entries={entries} total={total}/></section>
}
