'use client'
import { useState } from 'react'
import { MMI_DOMAINS } from '@/lib/interviews/mmi-rubric-v2'
import { mmiBand, type MMIFeedback, type MMIHighlight } from '@/lib/interviews/mmi-feedback'
import { MMIStudentFeedback } from './mmi-feedback-view'
import { MMIFeedbackEditor } from './mmi-feedback-editor'
import { setMMIDomainRating } from '@/lib/interviews/mmi-editor-state'
import { StudentFieldNote } from './mmi-review-guide'
const input='mt-2 w-full rounded-xl border border-border bg-background p-3 text-sm focus-visible:outline-2 focus-visible:outline-brand'
const requiredInput=(text:string)=>text.trim()?input:input.replace('border-border bg-background','border-amber-400 bg-amber-50')
const button='rounded-full border border-border px-4 py-2 text-sm transition-colors hover:bg-brand-muted focus-visible:outline-2 focus-visible:outline-brand'
export function MMIStudentDraft({value,onChange}:{value:MMIFeedback;onChange:(v:MMIFeedback)=>void}){
 const [preview,setPreview]=useState(false)
 function domainScore(key:MMIFeedback['domains'][number]['key'],raw:string){
  onChange(setMMIDomainRating(value,key,raw?Number(raw):null))
 }

 function points(field:'strengths'|'priorities',label:string){
  const available=value.domains.find(d=>d.status==='scored'&&d.evidence.length>0)
  const update=(index:number,patch:Partial<MMIHighlight>)=>onChange({...value,[field]:value[field].map((p,i)=>i===index?{...p,...patch}:p)})
  return <section className="space-y-3"><h3 className="font-semibold">{label}</h3><StudentFieldNote/>{!value[field].length&&<p className="text-sm text-muted">No points added. Include only points supported by this response.</p>}{value[field].map((p,i)=><div key={i} className="rounded-xl border border-border p-4"><label className="block text-sm">{label} · point {i+1}<textarea id={`mmi-${field}-${i}`} className={requiredInput(p.text)} aria-invalid={!p.text.trim()} placeholder={field==='strengths'?'Name something this student did well and explain why it worked.':'Build on their answer with a specific next step.'} rows={3} value={p.text} onChange={e=>update(i,{text:e.target.value})}/></label>{!p.text.trim()&&<StudentFieldNote empty>Write this point or remove it before approval.</StudentFieldNote>}<details className="mt-2 text-xs text-muted"><summary className="cursor-pointer">Supporting rubric point and evidence</summary><label className="mt-2 block">Domain<select className={input} value={p.domain} onChange={e=>{const d=value.domains.find(d=>d.key===e.target.value)!;update(i,{domain:d.key,references:[...new Set(d.evidence.flatMap(e=>e.references))]})}}>{value.domains.filter(d=>d.status==='scored').map(d=><option key={d.key} value={d.key}>{MMI_DOMAINS[d.key].label}</option>)}</select></label><label className="mt-2 block">Reference labels<input className={input} value={p.references.join(', ')} onChange={e=>update(i,{references:e.target.value.split(',').map(t=>t.trim()).filter(Boolean)})}/></label></details><button type="button" className="mt-2 text-xs text-muted hover:text-brand" onClick={()=>onChange({...value,[field]:value[field].filter((_,n)=>n!==i)})}>Remove point</button></div>)}{value[field].length<5&&available&&<button type="button" className={button} onClick={()=>onChange({...value,[field]:[...value[field],{domain:available.key,text:'',references:[...new Set(available.evidence.flatMap(e=>e.references))]}]})}>Add {field==='strengths'?'strength':'improvement'}</button>}</section>
 }
 return <section id="mmi-student-draft" tabIndex={-1} className="scroll-mt-6 space-y-5 rounded-2xl border border-border bg-surface p-5 sm:p-7" aria-label="Student feedback draft">
 <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-brand">Student report · review and edit</p><h2 className="font-display text-2xl font-semibold">Prepare student feedback</h2><p className="mt-2 max-w-2xl text-sm text-muted">Open the overall feedback with encouragement and a specific strength from this answer, then explain what to improve in words you’d use when giving the student feedback. Check the draft and scores before approving the report below.</p></div><button type="button" className={button} aria-pressed={preview} data-mmi-return-to-editing={preview?'':undefined} onClick={()=>setPreview(!preview)}>{preview?'Return to editing':'Preview student report'}</button></div>
 {preview?<MMIStudentFeedback approved={false} feedback={value}/>:<>
 <label className="block text-sm font-semibold">Overall score<StudentFieldNote>Student sees this score. Unscored is valid when evidence is insufficient.</StudentFieldNote><select aria-label="Overall score" className={input} value={value.global.score??''} onChange={e=>onChange({...value,global:{...value.global,status:e.target.value?'scored':'insufficient_evidence',score:e.target.value?Number(e.target.value):null}})}><option value="">Unscored — insufficient evidence</option>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} / 7 · {mmiBand(n)}</option>)}</select></label>
 <details className="text-sm"><summary className="cursor-pointer text-muted">Reason for the overall score · {value.global.score===null?'student sees this explanation':'tutor only'}{!value.global.reason.trim()?' · Needs writing':''}</summary><textarea id="mmi-global-reason" aria-label="Reason for overall score" aria-invalid={!value.global.reason.trim()} className={requiredInput(value.global.reason)} rows={2} value={value.global.reason} onChange={e=>onChange({...value,global:{...value.global,reason:e.target.value}})}/>{!value.global.reason.trim()&&<StudentFieldNote empty>Explain the score or why it is unscored.</StudentFieldNote>}</details>
 <section><h3 className="font-semibold">Domains assessed</h3><StudentFieldNote>Student sees the domain scores and any explanation of missing evidence.</StudentFieldNote><div className="mt-3 space-y-3">{value.domains.filter(d=>d.status!=='not_applicable').map(d=><div key={d.key} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label className="text-sm font-semibold" htmlFor={`draft-${d.key}`}>{MMI_DOMAINS[d.key].label}</label><select id={`draft-${d.key}`} className="rounded-lg border border-border bg-background p-2 text-sm" value={d.score??''} onChange={e=>domainScore(d.key,e.target.value)}><option value="">Unscored</option>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} / 7 · {mmiBand(n)}</option>)}</select></div><details className="mt-2 text-sm"><summary className="cursor-pointer text-muted">Scoring basis · tutor only{!d.rationale.trim()?' · Needs writing':''}</summary><textarea id={`mmi-rationale-${d.key}`} aria-label={`${MMI_DOMAINS[d.key].label} scoring comment`} aria-invalid={!d.rationale.trim()} className={requiredInput(d.rationale)} rows={3} value={d.rationale} onChange={e=>onChange({...value,domains:value.domains.map(v=>v.key===d.key?{...v,rationale:e.target.value}:v)})}/>{!d.rationale.trim()&&<StudentFieldNote empty>Add the scoring basis for your review record.</StudentFieldNote>}{d.score===null&&<label className="mt-3 block">Evidence needed<StudentFieldNote empty={!d.needed_evidence.trim()}>Student sees this explanation of what is missing.</StudentFieldNote><textarea id={`mmi-needed-${d.key}`} aria-invalid={!d.needed_evidence.trim()} className={requiredInput(d.needed_evidence)} rows={2} value={d.needed_evidence} onChange={e=>onChange({...value,domains:value.domains.map(v=>v.key===d.key?{...v,needed_evidence:e.target.value}:v)})}/></label>}</details></div>)}</div></section>
 <div className="grid gap-6 lg:grid-cols-2">{points('strengths','What you did well')}{points('priorities','What to improve')}</div>
 <label className="block text-sm font-semibold">Overall feedback<StudentFieldNote empty={!value.closing.verdict.trim()}>Student sees this. Start with encouragement and a specific strength, then give your overall feedback.</StudentFieldNote><textarea id="mmi-overall-feedback" aria-label="Overall feedback" aria-invalid={!value.closing.verdict.trim()} placeholder="Start with what they did well and what they can build on…" className={requiredInput(value.closing.verdict)} rows={3} value={value.closing.verdict} onChange={e=>onChange({...value,closing:{...value.closing,verdict:e.target.value}})}/></label>
 <label className="block text-sm">What successful improvement looks like<StudentFieldNote empty={!value.closing.successful_improvement.trim()}>Student sees this at the end of the overall comment. Make the next step clear.</StudentFieldNote><textarea id="mmi-next-step" aria-label="What successful improvement looks like" aria-invalid={!value.closing.successful_improvement.trim()} placeholder="Explain how they can strengthen this particular answer…" className={requiredInput(value.closing.successful_improvement)} rows={2} value={value.closing.successful_improvement} onChange={e=>onChange({...value,closing:{...value.closing,successful_improvement:e.target.value}})}/></label><p className="text-xs text-muted">These sentences form one overall comment. Any supported concerns are retained automatically.</p>
 {value.concerns.length>0&&<p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">Student also sees {value.concerns.length} supported concern or clarification in the overall comment. Review its wording and evidence in the detailed editor below.</p>}<details id="mmi-detailed-editor" tabIndex={-1} className="scroll-mt-6 border-t border-border pt-4"><summary className="cursor-pointer font-semibold">Detailed marking editor · domains, anchors and evidence</summary><div className="mt-5"><MMIFeedbackEditor value={value} onChange={onChange}/></div></details>
 </>}
 </section>
}
