'use client'
import {useState,useTransition,type MouseEvent} from 'react'
import {useRouter} from 'next/navigation'
import type {panelReviewDetail} from '@/lib/interviews/panel-data'
import {reviewPanelAction,retryPanelAction,refundPanelAction,classifyPanelResponseAction} from '@/lib/interviews/panel-actions'
import {retryInterviewAction} from '@/lib/interviews/marking-actions'
import {type PanelAssessment,type WholePanelFeedback,type PanelAudit} from '@/lib/interviews/panel-feedback'
import {PANEL_BANDS,WHOLE_PANEL_DOMAINS} from '@/lib/interviews/panel-rubric'
import {InterviewMediaPlayer} from './media-player'
import {WholePanelFeedbackView} from './panel-feedback-view'
type Detail=NonNullable<Awaited<ReturnType<typeof panelReviewDetail>>>
const auditLabels:Record<PanelAudit['warnings'][number]['category'],string>={evidence:'Evidence supporting the feedback',coverage:'Whether the question was answered',scoring:'Scores and rubric anchors',attribution:'Who said what',fairness:'Fairness and limits of the evidence',writing:'Feedback wording'}
const box='w-full rounded-xl border border-border bg-background p-3 text-sm leading-6 focus-visible:outline-2 focus-visible:outline-brand'
function openResponse(event:MouseEvent<HTMLAnchorElement>){const id=event.currentTarget.hash.slice(1),target=document.getElementById(id);if(target instanceof HTMLDetailsElement)target.open=true}
const button='min-h-11 rounded-full border border-border px-5 py-2 text-sm font-semibold hover:bg-brand-muted focus-visible:outline-2 focus-visible:outline-brand disabled:opacity-50'
export function PanelReviewEditor({detail}:{detail:Detail}){
 const {marking:m,members}=detail,assessment=m.assessment as PanelAssessment|null,audit=m.evidence_audit as PanelAudit|null
 const [feedback,setFeedback]=useState<WholePanelFeedback|null>((m.draft_feedback??assessment?.feedback) as WholePanelFeedback|null),[version,setVersion]=useState(m.lock_version),[notes,setNotes]=useState(m.private_reviewer_notes??''),[corrections,setCorrections]=useState(m.transcript_correction_notes??''),[checks,setChecks]=useState({watched:false,mapping:false,evidence:false,audit:false}),[message,setMessage]=useState(''),[closed,setClosed]=useState(['released','ungradable'].includes(m.status)),[busy,start]=useTransition(),[refundReason,setRefundReason]=useState('')
 const router=useRouter(),editable=!!feedback&&!!assessment&&!closed&&['processing','needs_attention','awaiting_review','in_review'].includes(m.status),refs=assessment?.source.sequences.flatMap(s=>s.references)??[]
 const allResponsesReady=members.every(a=>a.response_disposition||(a.transcription_status==='ready'&&!!a.transcript?.trim()))
 const awaitingTranscripts=['waiting_transcripts','needs_attention'].includes(m.status)
 const run=(action:()=>Promise<{ok:boolean;message:string}>)=>start(async()=>{try{const result=await action();setMessage(result.message);if(result.ok)router.refresh()}catch{setMessage('This action could not be completed. Your edits are still here.')}})
 const save=(action:'save'|'approve',destination:'next'|'dashboard'='next')=>start(async()=>{try{const r=await reviewPanelAction(m.id,version,action,feedback,notes,corrections,checks);setMessage(r.message);if(r.ok&&r.version!==undefined)setVersion(r.version);if(r.ok&&r.status!=='saved'){setClosed(true);router.push(destination==='dashboard'?'/admin':r.nextPath??'/admin/interviews')}else if(r.ok)router.refresh()}catch{setMessage('This action could not be completed. Your edits are still here.')}})
 const change=<K extends keyof WholePanelFeedback>(key:K,value:WholePanelFeedback[K])=>setFeedback(f=>f?{...f,[key]:value}:f)
 return <div className="space-y-7">
 <div className="rounded-2xl bg-brand-muted p-5"><h2 className="font-semibold">Review one panel interview</h2><p className="mt-2 text-sm leading-6">Read each question alongside its response and check the recordings. Compare the proposed scores and comments with the rubric and evidence. Review the automated suggestions, then edit and preview the student report. Save a private draft while you work; approve only when the complete report is ready.</p><p className="mt-2 text-sm">Status: {m.status.replaceAll('_',' ')} · {members.length} of 10 recordings</p>{awaitingTranscripts&&allResponsesReady&&!assessment&&<div className="mt-4 rounded-xl border border-brand/30 bg-background p-4"><p className="text-sm leading-6">Every response now has a transcript or a tutor-reviewed classification. Start AI marking when the classifications below are correct.</p><button disabled={busy} className={`${button} mt-3 bg-brand text-brand-foreground`} onClick={()=>run(()=>retryPanelAction(m.id,'assess'))}>Start AI marking</button></div>}</div>
 <section aria-label="Recordings and transcripts" className="rounded-2xl border border-border p-5"><h2 className="text-xl font-semibold">1. Recordings and transcript evidence · tutor only</h2><nav aria-label="Panel responses" className="my-4 flex flex-wrap gap-2">{members.map(a=><a className={button} key={a.id} onClick={openResponse} href={`#panel-Q${a.index+1}`}>Q{a.index+1}</a>)}</nav>
 {members.map(a=>{const seq=assessment?.source.sequences.find(s=>s.attempt_id===a.id),snapshot=a.station_snapshot as {preparation?:string;questions?:string[]},canClassify=!assessment&&awaitingTranscripts&&a.transcription_status==='failed'&&!a.transcript?.trim();return <details key={a.id} id={`panel-Q${a.index+1}`} className="scroll-mt-8 border-t border-border py-4"><summary className="cursor-pointer font-semibold">Q{a.index+1} · {a.station_title} · {a.response_disposition?a.response_disposition.replace('_',' '):a.transcription_status}</summary><div className="mt-4 space-y-4"><div className="rounded-xl bg-surface-muted p-4"><h3 className="font-semibold">Station brief / scenario</h3><p className="mt-2 whitespace-pre-wrap">{seq?.brief??snapshot.preparation??'No separate scenario supplied.'}</p><h3 className="mt-4 font-semibold">Interviewer questions</h3><ol className="mt-2 list-decimal space-y-2 pl-5">{(seq?.questions??snapshot.questions??[]).map((q,i)=><li key={i}>{q}</li>)}</ol></div>
 <InterviewMediaPlayer url={a.mediaUrl} kind={a.media_kind??'video'} events={[]} attemptId={a.id}/>
 <h3 className="font-semibold">Candidate response and supplied speaker turns</h3>{seq?<div className="space-y-3">{seq.references.filter(r=>r.speaker!=='prompt').map(r=><div id={`evidence-${r.id}`} key={r.id} className="scroll-mt-6 rounded-xl border border-border p-3"><p className="text-xs font-semibold text-brand">{r.id} · {r.speaker.replaceAll('_',' ')}{r.timestamp?` · ${r.timestamp}`:''}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{r.text}</p></div>)}</div>:<p className="whitespace-pre-wrap text-sm leading-6">{a.transcript??'Transcript not ready.'}</p>}
 {canClassify&&<section className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><h3 className="font-semibold">No usable transcript</h3><p className="mt-2 text-sm leading-6">Listen to the recording, then choose the finding that matches it. This stops transcript retries and records your decision for AI marking.</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy||a.response_disposition==='insubstantial'} className={button} onClick={()=>run(()=>classifyPanelResponseAction(m.id,a.id,'insubstantial'))}>Mark as insubstantial</button><button disabled={busy||a.response_disposition==='not_answered'} className={button} onClick={()=>run(()=>classifyPanelResponseAction(m.id,a.id,'not_answered'))}>Mark as not answered</button></div><p className="mt-3 text-xs leading-5"><strong>Insubstantial:</strong> some speech, but too little assessable content. <strong>Not answered:</strong> no answer was given.</p></section>}
 {a.transcription_status!=='ready'&&!closed&&!assessment&&<button disabled={busy} className={button} onClick={()=>run(()=>retryInterviewAction(a.id,'transcribe'))}>{a.response_disposition?'Retry transcription instead':'Retry transcription'}</button>}
 </div></details>})}</section>
 {assessment&&<details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Assessment plan and original model assessment · tutor only</summary><p className="mt-3">{assessment.plan.basis} plan · {assessment.plan.purpose}</p><p className="mt-2 text-sm">{assessment.plan.limitation}</p><ol className="mt-3 space-y-2 text-sm">{assessment.plan.tasks.map(t=><li key={t.sequence}><a onClick={openResponse} href={`#panel-${t.sequence}`} className="text-brand">{t.sequence}</a> · {t.primary?'Primary':'Supporting'} · {t.essential} {t.optional&&`Optional: ${t.optional}`}</li>)}</ol><pre className="mt-4 max-h-96 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(assessment.feedback,null,2)}</pre></details>}
 <section aria-label="Evidence audit suggestions" className="rounded-2xl border border-border p-5">
 <h2 className="text-xl font-semibold">2. Evidence audit · suggested checks for the tutor</h2>
 <p className="mt-3 text-sm leading-6">A second automated check compares the draft feedback with the answers and rubric. Its suggestions can be wrong or incomplete. They are private, do not change scores, and do not approve the report.</p>
 {audit?<>
 <p className="mt-3 font-semibold">{audit.warnings.length?`${audit.warnings.length} suggested ${audit.warnings.length===1?'check':'checks'} to review`:'No discrepancies reported by the automated check'}</p>
 <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6"><li>Read each suggestion and open any linked answer. Check the exact wording against the proposed feedback.</li><li>If it identifies a real problem, correct the score or student wording below. If it is mistaken or too vague, explain why in your private review notes.</li><li>Record your decision for each suggestion before confirming the audit review. Even a clear audit still needs your evidence check.</li></ol>
 <ul className="mt-4 space-y-4">{audit.warnings.map((w,i)=><li key={i} className="rounded-xl bg-amber-50 p-4 text-amber-950"><h3 className="font-semibold">Check {i+1} · {auditLabels[w.category]}</h3><p className="mt-2 text-xs font-semibold">Automated suggestion · verify before acting</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{w.detail}</p>{w.references.length>0?<div className="mt-3"><p className="text-xs font-semibold">Linked source · check that it supports the suggestion</p><div className="mt-2 flex flex-wrap gap-3">{w.references.map(r=><a key={r} onClick={openResponse} href={`#panel-${r.split('-')[0]}`} className="underline">Open {r}</a>)}</div></div>:<p className="mt-3 text-xs">Report-wide suggestion · no answer linked</p>}</li>)}</ul>
 <details className="mt-4 text-sm leading-6"><summary className="cursor-pointer font-semibold">How to handle unclear or mistaken suggestions</summary><p className="mt-2">A reminder to “check the evidence” is not a finding that the evidence is wrong. Look for a specific claim, the relevant answer and an explanation of the mismatch. Record any actual problem you find, or explain that the suggestion did not identify one.</p><p className="mt-2">The standard “Reviewed and approved” note is reserved for the released report. Draft previews show “Requires tutor approval before release.” The reserved note alone does not mean a report was released early and does not need to be removed.</p></details>
 </>:<p className="mt-3">The automated check is not available yet. You can review, edit and save the AI draft now; release remains unavailable until the audit finishes.</p>}
 </section>
 {feedback&&<fieldset disabled={!editable||busy} className="min-w-0 space-y-6 disabled:opacity-70"><legend className="mb-4 text-xl font-semibold">3. Student report · review and edit every section</legend>
 <p className="rounded-xl bg-brand-muted p-4 text-sm leading-6">Write directly to your student, as you would in a tutorial. Start the overall feedback with encouragement and any praise the answer supports, then explain what to work on. Use “I liked how you…” or “I’d like you to explain…” where it fits, and make each comment about their answer. Match the encouragement to the answer. State major gaps plainly, vary your openings, and avoid inventing a weakness in a strong response. Check that every compliment and suggestion matches the evidence.</p>
 <details open className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Question coverage · student can expand to read</summary><p className="mt-3 text-sm leading-6">These comments appear under “Evidence scope and question coverage” in the student report, collapsed by default. Each comment is a proposed message to the student for you to edit. Begin with brief encouragement or earned praise, then give your direct judgement using “I” and “you”. Explain what worked or was missing and what would improve the answer. Keep praise proportionate and vary the openings. This is not a separate question score.</p><p className="mt-2 text-sm leading-6"><strong>Addressed:</strong> answered the essential task, even if the quality was weak. <strong>Partly addressed:</strong> answered only part of the task. <strong>Not addressed:</strong> the available response did not answer the task. <strong>Not assessable:</strong> the evidence is missing or unusable. Credit later corrections in the whole-panel judgement without rewriting what the original answer covered.</p><div className="mt-4 space-y-4">{feedback.question_coverage.map((q,i)=><div key={q.sequence} className="grid gap-3 rounded-xl bg-surface p-4 sm:grid-cols-[180px_1fr]"><div><a onClick={openResponse} href={`#panel-${q.sequence}`} className="font-semibold text-brand">{q.sequence} · {q.topic} ↗</a><select aria-label={`${q.sequence} coverage`} className={`${box} mt-2`} value={q.coverage} onChange={e=>change('question_coverage',feedback.question_coverage.map((r,j)=>j===i?{...r,coverage:e.target.value as typeof q.coverage}:r))}>{['addressed','partly_addressed','not_addressed','not_assessable'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></div><Text label={`${q.sequence} coverage comment`} value={q.observation} onChange={observation=>change('question_coverage',feedback.question_coverage.map((r,j)=>j===i?{...r,observation}:r))}/></div>)}</div></details>
 <div className="space-y-3">{feedback.domains.map((d,i)=>{const update=(v:Partial<typeof d>)=>change('domains',feedback.domains.map((r,j)=>j===i?{...r,...v}:r)),elicited=assessment?.plan.tasks.some(t=>t.domains.includes(d.key));return <details key={d.key} className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">{d.label} · {d.score??d.state.replaceAll('_',' ')}</summary><div className="mt-4 space-y-4"><p className="text-sm text-muted">State, score, explanation and improvement are student-visible. Source links remain in the tutor workspace.</p><div className="flex flex-wrap gap-4"><label>Evidence state<select className={`${box} mt-2`} value={d.state} onChange={e=>update({state:e.target.value as typeof d.state,score:null})}>{(elicited?['scored','insufficient_evidence']:['not_elicited']).map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label>{d.state==='scored'&&<label>Integer score<select className={`${box} mt-2`} value={d.score??''} onChange={e=>update({score:e.target.value?Number(e.target.value):null})}><option value="">Choose score</option>{PANEL_BANDS.map((b,n)=><option key={b} value={n+1}>{n+1} · {b}</option>)}</select></label>}</div>
 <details><summary className="cursor-pointer text-sm font-semibold">Scoring anchors</summary><ol className="mt-2 space-y-2 text-sm">{Object.entries(WHOLE_PANEL_DOMAINS[d.key].anchors).map(([n,a])=><li key={n}><strong>{n}.</strong> {a}</li>)}</ol></details>
 <Text label="Why this score or evidence state · student sees this" value={d.why} onChange={why=>update({why})}/><Text label="Specific improvement · student sees this" value={d.improvement} onChange={improvement=>update({improvement})}/>
 <details><summary className="cursor-pointer text-sm font-semibold">Supporting evidence · {d.evidence.length} references selected</summary><div className="mt-3 max-h-80 space-y-3 overflow-y-auto">{refs.map(r=><label key={r.id} className="flex gap-3 rounded-xl bg-surface-muted p-3 text-sm"><input type="checkbox" checked={d.evidence.includes(r.id)} onChange={e=>update({evidence:e.target.checked?[...d.evidence,r.id]:d.evidence.filter(id=>id!==r.id)})}/><span><strong>{r.id} · {r.speaker}</strong><span className="mt-1 block whitespace-pre-wrap">{r.text}</span></span></label>)}</div></details></div></details>})}</div>
 <section className="space-y-4 rounded-2xl border border-brand/40 bg-surface p-5"><h3 className="font-semibold">Overall rating and feedback · student sees this</h3><label className="block">Whole-panel rating<select className={`${box} mt-2`} value={feedback.global_rating.score??''} onChange={e=>{const score=e.target.value?Number(e.target.value):null;change('global_rating',{...feedback.global_rating,score,band:score===null?null:PANEL_BANDS[score-1]})}}><option value="">Unavailable · insufficient evidence</option>{PANEL_BANDS.map((b,n)=><option key={b} value={n+1}>{n+1} · {b}</option>)}</select></label><Text label="Rating basis (explain why if unavailable)" value={feedback.global_rating.basis} onChange={basis=>change('global_rating',{...feedback.global_rating,basis})}/>
 <Lines label="What you did well" values={feedback.strengths} onChange={v=>change('strengths',v)}/><Lines label="What to improve" values={feedback.priorities} onChange={v=>change('priorities',v)}/><Text label="Overall feedback · one concise paragraph" value={feedback.closing_paragraph} onChange={v=>change('closing_paragraph',v)}/><p className="text-sm text-muted">Start with encouragement grounded in this response. Combine the verdict, what successful improvement looks like and any supported concern. Identify the question when discussing a concern. No practice exercises.</p></section>
 <section className="space-y-4 rounded-2xl border border-border p-5"><h3 className="font-semibold">Concern evidence · tutor only; include supported concerns in the student’s overall feedback</h3>{feedback.concerns.map((c,i)=><div key={i} className="space-y-3 rounded-xl bg-surface-muted p-4"><label>Question<select className={`${box} mt-2`} value={c.sequence} onChange={e=>change('concerns',feedback.concerns.map((r,j)=>j===i?{...r,sequence:e.target.value}:r))}>{feedback.question_coverage.map(q=><option key={q.sequence}>{q.sequence}</option>)}</select></label><label>Level<select className={`${box} mt-2`} value={c.level} onChange={e=>change('concerns',feedback.concerns.map((r,j)=>j===i?{...r,level:e.target.value as typeof c.level}:r))}>{['clarification_needed','observed_concern','serious_observed_concern'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><Text label="Concern and supporting context" value={c.detail} onChange={detail=>change('concerns',feedback.concerns.map((r,j)=>j===i?{...r,detail}:r))}/><button className={button} onClick={()=>change('concerns',feedback.concerns.filter((_,j)=>j!==i))}>Remove concern</button></div>)}<button className={button} disabled={feedback.concerns.length>=12} onClick={()=>change('concerns',[...feedback.concerns,{sequence:'Q1',level:'clarification_needed',detail:''}])}>Add concern</button></section>
 <div className="space-y-2"><Text label="Private reviewer notes / audit resolutions · never shown to the student" value={notes} onChange={setNotes}/><p className="text-sm leading-6 text-muted">For each suggested check, note the check number, what you verified, and what you changed or why no change was needed. These notes are for the review record, not the student report.</p></div><Text label="Transcript correction notes · never shown to the student" value={corrections} onChange={setCorrections}/>
 <WholePanelFeedbackView feedback={feedback} preview={m.status!=='released'}/>
 <section className="space-y-4 rounded-2xl border border-brand/40 p-5"><h3 className="font-semibold">4. Confirm review before releasing</h3>{([['watched','I inspected the complete available recording set.'],['mapping','I checked all questions, speakers and transcript mappings.'],['evidence','I checked the decisive evidence, scores and student wording.'],['audit','I reviewed and resolved or documented the audit warnings.']] as const).map(([key,label])=><label key={key} className="flex gap-3 text-sm"><input type="checkbox" disabled={key==='audit'&&!audit} checked={checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/>{label}</label>)}<div className="flex flex-wrap gap-3"><button className={button} onClick={()=>save('save')}>Save private draft</button><button className={`${button} bg-brand text-brand-foreground`} disabled={!audit||!Object.values(checks).every(Boolean)} onClick={()=>save('approve','next')}>Approve &amp; open next marking</button><button className={button} disabled={!audit||!Object.values(checks).every(Boolean)} onClick={()=>save('approve','dashboard')}>Approve &amp; return to admin dashboard</button></div>{!audit&&<p className="text-sm text-muted">You can save your edits now. Approval becomes available after the evidence audit finishes.</p>}</section>
 </fieldset>}
 <p role="status" aria-live="polite" className="font-semibold">{message}</p>
 {!closed&&<details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Processing recovery and refund</summary><p className="mt-3 text-sm">Retrying an assessment replaces its automatic draft. Retries are blocked while a tutor is editing. A refund closes this panel as ungradable.</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} className={button} onClick={()=>run(()=>retryPanelAction(m.id,'assess'))}>Retry whole-panel assessment</button><button disabled={busy} className={button} onClick={()=>run(()=>retryPanelAction(m.id,'audit'))}>Retry evidence audit</button></div><div className="mt-4"><Text label="Reason this panel cannot be graded" value={refundReason} onChange={setRefundReason}/><button disabled={busy||!refundReason.trim()} className={`${button} mt-3`} onClick={()=>run(async()=>{const r=await refundPanelAction(m.id,refundReason);if(r.ok)setClosed(true);return r})}>Mark ungradable &amp; refund</button></div></details>}
 <details className="rounded-2xl border border-border p-5"><summary className="cursor-pointer font-semibold">Processing and review history · tutor only</summary><ul className="mt-3 space-y-2 text-sm">{detail.jobs.map(j=><li key={j.id}>{j.job_type} · {j.status} · {j.attempt_count} attempts · {j.last_error_code}</li>)}{detail.transcriptionJobs.map(j=><li key={j.id}>Transcript {members.find(a=>a.id===j.attempt_id)?.index!==undefined?`Q${members.find(a=>a.id===j.attempt_id)!.index+1}`:''} · {j.status} · {j.last_error_code}</li>)}{detail.events.map(e=><li key={e.id}>{new Date(e.created_at).toLocaleString('en-AU')} · {e.event_type}</li>)}</ul></details>
 </div>
}
function Text({label,value,onChange}:{label:string;value:string;onChange:(s:string)=>void}){return <label className="block text-sm font-semibold">{label}<textarea className={`${box} mt-2 font-normal`} value={value} rows={3} maxLength={2000} onChange={e=>onChange(e.target.value)}/></label>}
function Lines({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){return <div className="space-y-3"><h4 className="font-semibold">{label}</h4>{values.map((v,i)=><div key={i} className="space-y-2"><Text label={`${label} · point ${i+1}`} value={v} onChange={s=>onChange(values.map((r,j)=>j===i?s:r))}/><button className={button} onClick={()=>onChange(values.filter((_,j)=>j!==i))}>Remove point</button></div>)}<button className={button} disabled={values.length>=5} onClick={()=>onChange([...values,''])}>Add point</button></div>}
