import type {WholePanelFeedback} from '@/lib/interviews/panel-feedback'
export type PanelReport={sessionId:string;status:string;feedback:WholePanelFeedback|null}
export function WholePanelFeedbackView({feedback,preview=false}:{feedback:WholePanelFeedback;preview?:boolean}){
 return <section aria-label={preview?'Student report preview':'Whole-panel feedback'} className="space-y-6 rounded-2xl border border-border bg-surface p-5 sm:p-7">
 <header><p className="text-sm font-semibold text-brand">{preview?'Student preview · unreleased draft':'Whole-panel feedback'}</p><h2 className="mt-2 font-display text-3xl font-semibold">{feedback.global_rating.score===null?'Global rating unavailable':`${feedback.global_rating.score} / 7 · ${feedback.global_rating.band}`}</h2><p className="mt-3 leading-7">{feedback.global_rating.basis}</p></header>
 <details><summary className="cursor-pointer font-semibold">Evidence scope and question coverage</summary><p className="mt-3 text-sm leading-6">Transcript assessment · {feedback.evidence_scope.completeness}. {feedback.evidence_scope.limitation}</p><ol className="mt-3 divide-y divide-border">{feedback.question_coverage.map(q=><li key={q.sequence} className="py-3 text-sm"><strong>{q.sequence} · {q.topic}</strong><span className="ml-2 text-muted">{q.coverage.replaceAll('_',' ')}</span><p className="mt-1">{q.observation}</p></li>)}</ol></details>
 <div><h3 className="font-semibold">Domains assessed</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{feedback.domains.filter(d=>d.state!=='not_elicited').map(d=><article key={d.key} className="rounded-xl border border-border p-4"><h4 className="font-semibold">{d.label} <span className="text-brand">{d.score===null?'· Insufficient evidence':`· ${d.score} / 7`}</span></h4><p className="mt-2 text-sm leading-6">{d.why}</p>{d.improvement&&<p className="mt-2 text-sm leading-6">{d.improvement}</p>}</article>)}</div>{feedback.domains.some(d=>d.state==='not_elicited')&&<p className="mt-3 text-sm text-muted">These questions didn&apos;t ask about: {feedback.domains.filter(d=>d.state==='not_elicited').map(d=>d.label).join(', ')}.</p>}</div>
 <div className="grid gap-6 sm:grid-cols-2"><Points title="What you did well" values={feedback.strengths}/><Points title="What to improve" values={feedback.priorities}/></div>
 <div className="rounded-xl bg-brand-muted p-5"><h3 className="font-semibold">Overall feedback</h3><p className="mt-3 leading-7">{feedback.closing_paragraph}</p></div>
 <p className="text-sm text-muted">{preview?'Requires tutor approval before release.':feedback.reviewer_note} Feedback is for practice and does not predict admission.</p>
 </section>
}
function Points({title,values}:{title:string;values:string[]}){return <div><h3 className="font-semibold">{title}</h3><ul className="mt-3 list-disc space-y-3 pl-5 leading-7">{values.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}
export function PanelReportView({report}:{report:PanelReport}){return report.feedback?<WholePanelFeedbackView feedback={report.feedback}/>:<section className="rounded-2xl bg-surface p-5" role="status"><h2 className="font-semibold">Whole-panel feedback</h2><p className="mt-2">{report.status==='unavailable'?'Your report could not be loaded. Please try again.':report.status==='ungradable'?'This panel could not be marked. Any marking credits charged for it have been refunded.':report.status==='released'?'Your released report could not be displayed. Please contact support.':'Your full panel is in marking. Your tutor will release one report after reviewing all ten responses.'}</p></section>}
