'use client'
import {useRef,useState} from 'react'
import {STORY_PROMPTS,STORY_PROMPT_CATEGORIES,storyPromptCategory,type StoryPrompt} from '@/lib/interviews/story-prompts'
import {isStoryAnswered,storyPromptStatus,type InterviewStory,type StoryPromptStatus} from '@/lib/interviews/stories'
import {haptic} from '@/lib/haptics'
import {InterviewWorkspaceMotion} from './workspace-motion'
import styles from './story-prompt-library.module.css'
const control='min-h-11 rounded-full border border-border bg-surface px-4 text-sm outline-none focus-visible:ring-2 focus-visible:ring-brand/40'
const labels:Record<StoryPromptStatus,string>={'not-started':'Not started','in-progress':'In progress',answered:'Answered'}
export function StoryStatus({status}:{status:StoryPromptStatus}){
 return <span className={`inline-flex shrink-0 items-center gap-1.5 text-xs font-medium ${status==='answered'?'text-mint-deep':status==='in-progress'?'text-brand':'text-muted'}`}>{status==='answered'&&<svg aria-hidden width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m4 10 4 4 8-8"/></svg>}{labels[status]}</span>
}
export function StoryPromptLibrary({stories,loading,onPrompt,onStory,onCreate}:{stories:InterviewStory[];loading:boolean;onPrompt:(prompt:StoryPrompt)=>void;onStory:(story:InterviewStory)=>void;onCreate:()=>void}){
 const resultsHeading=useRef<HTMLHeadingElement>(null)
 const [tab,setTab]=useState<'prompts'|'stories'>('prompts'),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[revealed,setRevealed]=useState<Set<string>>(()=>new Set())
 const search=query.trim().toLowerCase(),answered=STORY_PROMPTS.filter(p=>storyPromptStatus(stories,p.id)==='answered').length
 const matches=(values:string[])=>values.join(' ').toLowerCase().includes(search)
 const prompts=STORY_PROMPTS.filter(p=>(!category||p.category===category)&&(status==='all'||storyPromptStatus(stories,p.id)===status)&&matches([p.text,storyPromptCategory(p.category),...stories.filter(s=>s.prompt_id===p.id).flatMap(s=>[s.title,s.context,s.actions,s.reflection])]))
 const saved=stories.filter(s=>(!category||STORY_PROMPTS.some(p=>p.id===s.prompt_id&&p.category===category))&&(status==='all'||(isStoryAnswered(s)?'answered':'in-progress')===status)&&matches([s.title,s.context,s.actions,s.reflection,s.theme,STORY_PROMPTS.find(p=>p.id===s.prompt_id)?.text??'']))
 const count=tab==='prompts'?prompts.length:saved.length,pages=Math.max(1,Math.ceil(count/10)),current=Math.min(page,pages),offset=(current-1)*10
 function changePage(value:number){setPage(value);requestAnimationFrame(()=>{resultsHeading.current?.focus({preventScroll:true});resultsHeading.current?.scrollIntoView({block:'start',behavior:'instant'})})}
 function chooseCategory(value:string){setCategory(value);setPage(1)}
 function chooseTab(value:'prompts'|'stories'){setTab(value);setCategory('');setStatus('all');setPage(1)}
 function revealPrompt(id:string){haptic(9);setRevealed(previous=>{const next=new Set(previous);next.add(id);return next})}
 const categories=<><option value="">All themes</option>{STORY_PROMPT_CATEGORIES.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</>
 return <InterviewWorkspaceMotion>
  <div data-interview-scroll-reveal className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-4">
   <div className="flex gap-2" aria-label="Story library view">{([['prompts','Prompt library',STORY_PROMPTS.length],['stories','Your stories',stories.length]] as const).map(([value,label,total])=><button key={value} type="button" aria-pressed={tab===value} onClick={()=>chooseTab(value)} className={`eb-press min-h-11 rounded-full px-4 text-sm font-semibold outline-none focus-visible:ring-2 focus-visible:ring-brand/40 ${tab===value?'bg-brand text-brand-foreground':'text-muted hover:bg-surface-muted'}`}>{label} <span className="ml-1 tabular-nums opacity-80">{total}</span></button>)}</div>
   <button className="eb-press min-h-11 rounded-full border border-border bg-surface px-4 text-sm font-semibold hover:bg-brand-muted focus-visible:outline-brand" onClick={onCreate}>Add your own story</button>
  </div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[230px_minmax(0,1fr)]">
   <nav aria-label="Story themes" className="hidden lg:block"><p className="mb-3 text-sm font-semibold">Browse themes</p><button onClick={()=>chooseCategory('')} aria-current={!category?'true':undefined} className={`mb-1 flex min-h-11 w-full items-center justify-between rounded-lg px-3 text-left text-sm ${!category?'bg-brand-muted font-semibold text-brand':'hover:bg-surface-muted'}`}>All themes <span className="text-xs tabular-nums">{tab==='prompts'?STORY_PROMPTS.length:stories.length}</span></button>{STORY_PROMPT_CATEGORIES.map(c=>{const total=tab==='prompts'?STORY_PROMPTS.filter(p=>p.category===c.id).length:stories.filter(s=>STORY_PROMPTS.some(p=>p.id===s.prompt_id&&p.category===c.id)).length;return <button key={c.id} onClick={()=>chooseCategory(c.id)} aria-current={category===c.id?'true':undefined} className={`flex min-h-11 w-full items-center justify-between gap-2 rounded-lg px-3 py-2 text-left text-sm leading-5 outline-none focus-visible:ring-2 focus-visible:ring-brand/40 ${category===c.id?'bg-brand-muted font-semibold text-brand':'text-muted hover:bg-surface-muted'}`}><span>{c.label}</span><span className="text-xs tabular-nums">{total}</span></button>})}</nav>
   <div className="min-w-0">
    <div className="flex flex-col gap-3 sm:flex-row"><label className="min-w-0 flex-1"><span className="sr-only">Search prompts and stories</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search prompts or your own words" className={`${control} w-full`}/></label><label><span className="sr-only">Answer status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className={`${control} w-full`}><option value="all">All statuses</option>{tab==='prompts'&&<option value="not-started">Not started</option>}<option value="in-progress">In progress</option><option value="answered">Answered</option></select></label></div>
    <label className="mt-3 block lg:hidden"><span className="sr-only">Story theme</span><select aria-label="Story theme" value={category} onChange={e=>chooseCategory(e.target.value)} className={`${control} w-full`}>{categories}</select></label>
    <div className="my-5 flex flex-wrap items-baseline justify-between gap-2"><h2 ref={resultsHeading} tabIndex={-1} className="scroll-mt-24 text-lg font-semibold outline-none">{category?storyPromptCategory(category):tab==='prompts'?'Find an experience to reflect on':'Your saved experiences'}</h2><p className="text-xs text-muted" role="status">{loading?'Checking saved answers…':tab==='prompts'?`${answered} of ${STORY_PROMPTS.length} prompts answered`:`${stories.length} saved stories`}</p></div>
    {loading&&tab==='stories'&&!stories.length?<p className="py-10 text-sm text-muted">Loading your stories…</p>:count===0?<div className="rounded-xl bg-surface px-5 py-10"><h3 className="font-semibold">{tab==='stories'&&!stories.length?'Your experiences will appear here':'No matches found'}</h3><p className="mt-2 text-sm leading-6 text-muted">{tab==='stories'&&!stories.length?'Choose a prompt to begin, or add a story of your own. You can save a little now and come back later.':'Try a different theme, status or search.'}</p>{(query||category||status!=='all')&&<button onClick={()=>{setQuery('');setCategory('');setStatus('all');setPage(1)}} className="mt-3 min-h-11 text-sm font-semibold text-brand">Clear filters</button>}</div>:<ul className={styles.results}>
     {tab==='prompts'?prompts.slice(offset,offset+10).map((p,index)=>{const shown=revealed.has(p.id);return <li key={p.id} className={styles.promptCard} data-revealed={shown||undefined} data-interview-scroll-reveal data-interview-parallax-section><article className={styles.promptInner}>
      <span className={styles.promptNumber} data-interview-parallax="8" aria-hidden>{String(offset+index+1).padStart(2,'0')}</span>
      <div className={styles.promptCopy}>{shown?<><span className={styles.revealedLabel}>Prompt revealed</span><h3>{p.text}</h3></>:<><span className={styles.hiddenLabel}>Unseen prompt</span><h3>Prompt hidden until you choose to reveal it.</h3></>}<div className={styles.promptMeta}><span>{storyPromptCategory(p.category)}</span><StoryStatus status={storyPromptStatus(stories,p.id)}/></div></div>
      {shown?<button disabled={loading} data-haptic="confirm" onClick={()=>onPrompt(p)} className={styles.usePrompt}>Use this prompt <Arrow/></button>:<button disabled={loading} data-haptic="soft" onClick={()=>revealPrompt(p.id)} className={styles.revealPrompt}>Reveal prompt <Eye/></button>}
     </article></li>}):saved.slice(offset,offset+10).map(s=><li key={s.id} className={styles.savedCard}><button onClick={()=>onStory(s)} className="group flex min-h-24 w-full items-center gap-4 px-5 py-4 text-left outline-none focus-visible:ring-2 focus-visible:ring-brand/40"><span className="min-w-0 flex-1"><span className="block break-words text-base font-semibold">{s.title}</span><span className="mt-1.5 flex flex-wrap gap-x-4 gap-y-1"><span className="text-xs text-muted">{STORY_PROMPTS.find(p=>p.id===s.prompt_id)?storyPromptCategory(STORY_PROMPTS.find(p=>p.id===s.prompt_id)!.category):s.theme}</span><StoryStatus status={isStoryAnswered(s)?'answered':'in-progress'}/></span><span className="mt-2 line-clamp-1 text-sm text-muted">{s.reflection||s.actions||s.context}</span></span><Arrow/></button></li>)}
    </ul>}
    {count>0&&<nav aria-label="Story library pages" className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted">{offset+1}–{Math.min(offset+10,count)} of {count} {tab==='prompts'?'prompts':'stories'}</p>{pages>1&&<div className="flex items-center gap-3"><button className={`${control} disabled:opacity-40 hover:bg-surface-muted`} disabled={current===1} onClick={()=>changePage(current-1)}>Previous</button><span className="text-xs tabular-nums text-muted">{current} / {pages}</span><button className={`${control} disabled:opacity-40 hover:bg-surface-muted`} disabled={current===pages} onClick={()=>changePage(current+1)}>Next</button></div>}</nav>}
   </div>
  </div>
 </InterviewWorkspaceMotion>
}
function Arrow(){return <svg aria-hidden className="shrink-0 text-brand transition-transform group-hover:translate-x-0.5 motion-reduce:transform-none" width="18" height="18" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4 10h12m-5-5 5 5-5 5"/></svg>}
function Eye(){return <svg aria-hidden width="17" height="17" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2.5 10s2.6-4.5 7.5-4.5 7.5 4.5 7.5 4.5-2.6 4.5-7.5 4.5S2.5 10 2.5 10Z"/><circle cx="10" cy="10" r="2"/></svg>}
