import { MMI_BANDS,MMI_DOMAINS,MMI_FEEDBACK_VERSION,MMI_RUBRIC_VERSION,type MMIDomainKey } from './mmi-rubric-v2'
import type { MMISource,MMISpeaker,MMIReference } from './mmi-evidence'
import { validateSchema } from './marking-validation'
export type MMIEvidence={kind:'quote'|'paraphrase'|'omission';speaker:MMISpeaker;text:string;references:string[]}
export type MMISpecification={task:string;role:string;basis:'supplied'|'provisional'|'inferred';primary_domains:Array<{key:MMIDomainKey;reason:string}>;essential_expectations:string[];optional_enrichment:string[];acceptable_approaches:string[];interaction_conditions:string;limitations:string[]}
export type MMIDomain={key:MMIDomainKey;status:'scored'|'insufficient_evidence'|'not_applicable';score:number|null;evidence:MMIEvidence[];rationale:string;improvement:string;needed_evidence:string}
export type MMIHighlight={domain:MMIDomainKey;text:string;references:string[]}
export type MMIConcern={id:string;status:'clarification_needed'|'observed_concern'|'serious_observed_concern';description:string;consequence:string;certainty:'clear'|'uncertain';repair:string;evidence:MMIEvidence[]}
export type MMIReviewerEvidence={id:string;speaker:MMISpeaker;text:string;timestamp:string|null;media:'audio'|'video';kind:'observation'|'transcript_correction'}
export type MMIReviewerScope={media_inspected:'none'|'audio'|'video';completeness:'complete'|'partial'|'unknown';primary_task_coverage:'full'|'excerpt'|'unknown'}
export type MMIFeedback={reviewer_evidence:MMIReviewerEvidence[];reviewer_scope:MMIReviewerScope;format_version:typeof MMI_FEEDBACK_VERSION;rubric_version:typeof MMI_RUBRIC_VERSION;format:'mmi';station_id:string;specification:MMISpecification;source:MMISource;domains:MMIDomain[];global:{status:'scored'|'insufficient_evidence';score:number|null;reason:string};strengths:MMIHighlight[];priorities:MMIHighlight[];concerns:MMIConcern[];closing:{verdict:string;successful_improvement:string}}
export type MMIAssessment={format:'mmi';station_id:string;feedback:MMIFeedback}
export type MMIAudit={format_version:'mmi-audit-v2';warnings:Array<{category:'quotation'|'attribution'|'omission'|'expectations'|'scoring'|'overlap'|'concern'|'fairness'|'summary'|'uncertainty';domain:MMIDomainKey|null;references:string[];detail:string}>;requires_human_attention:boolean}
const str={type:'string',maxLength:3000} as const
const object=(properties:Record<string,unknown>)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false})
const list=(items:unknown,maxItems=20)=>({type:'array',items,maxItems})
const enumeration=(values:readonly unknown[])=>({type:'string',enum:values})
const keys=Object.keys(MMI_DOMAINS)
const key=enumeration(keys),refs=list({type:'string',maxLength:80},30)
const evidenceRefs={...refs,minItems:1}
const score={anyOf:[{type:'integer',minimum:1,maximum:7},{type:'null'}]}
const evidence=object({kind:enumeration(['quote','paraphrase','omission']),speaker:enumeration(['candidate','actor','interviewer','recording_note','unknown','prompt']),text:str,references:evidenceRefs})
export const MMI_SPEC_SCHEMA=object({task:str,role:str,basis:enumeration(['supplied','provisional','inferred']),primary_domains:list(object({key,reason:str}),12),essential_expectations:list(str,8),optional_enrichment:list(str,8),acceptable_approaches:list(str,8),interaction_conditions:str,limitations:list(str,10)})
// Source and locked specification are attached by the server, never generated by the model.
export const MMI_MARK_SCHEMA=object({domains:list(object({key,status:enumeration(['scored','insufficient_evidence','not_applicable']),score,evidence:list(evidence,2),rationale:str,improvement:str,needed_evidence:str}),12),global:object({status:enumeration(['scored','insufficient_evidence']),score,reason:str}),strengths:list(object({domain:key,text:str,references:evidenceRefs}),5),priorities:list(object({domain:key,text:str,references:evidenceRefs}),5),concerns:list(object({id:{type:'string',maxLength:40},status:enumeration(['clarification_needed','observed_concern','serious_observed_concern']),description:str,consequence:str,certainty:enumeration(['clear','uncertain']),repair:str,evidence:list(evidence,3)}),8),closing:object({verdict:str,successful_improvement:str})})
/** Generated marks may only cite IDs from the supplied transcript and prompts. */
export function mmiMarkSchemaFor(source:MMISource,specification?:MMISpecification){
 const ids=[...new Set(source.references.map(r=>r.id))]
 const sourceRefs=ids.length>0&&ids.length<=150?{...evidenceRefs,items:enumeration(ids)}:evidenceRefs
 const groundedEvidence=object({kind:enumeration(source.completeness==='complete'?['quote','paraphrase','omission']:['quote','paraphrase']),speaker:enumeration(['candidate','actor','interviewer','recording_note','unknown','prompt']),text:{...str,minLength:1},references:sourceRefs})
 const selected=specification?specification.primary_domains.map(d=>d.key):keys
 const unselected=keys.filter(k=>!selected.includes(k as MMIDomainKey))
 const common={key:enumeration(selected),rationale:{...str,minLength:1}}
 const variants=[
  ...(source.response_disposition==='insubstantial'?[]:[object({...common,status:enumeration(['scored']),score:{type:'integer',minimum:1,maximum:7},evidence:{...list(groundedEvidence,2),minItems:1},improvement:{...str,minLength:1},needed_evidence:str})]),
  object({...common,status:enumeration(['insufficient_evidence']),score:{type:'null'},evidence:list(groundedEvidence,2),improvement:enumeration(['']),needed_evidence:{...str,minLength:1}}),
 ]
 if(unselected.length)variants.push(object({...common,key:enumeration(unselected),status:enumeration(['not_applicable']),score:{type:'null'},evidence:list(groundedEvidence,2),improvement:enumeration(['']),needed_evidence:str}))
 const unscoredGlobal=object({status:enumeration(['insufficient_evidence']),score:{type:'null'},reason:{...str,minLength:1}})
 const global=source.primary_task_coverage==='excerpt'||source.response_disposition==='insubstantial'?unscoredGlobal:{anyOf:[object({status:enumeration(['scored']),score:{type:'integer',minimum:1,maximum:7},reason:{...str,minLength:1}}),unscoredGlobal]}
 const schema=object({...MMI_MARK_SCHEMA.properties,domains:{...list({anyOf:variants},12),minItems:1},global})
 const constrain=(value:unknown):unknown=>{
  if(Array.isArray(value))return value.map(constrain)
  if(value!==null&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([name,item])=>[name,name==='references'?sourceRefs:name==='kind'?groundedEvidence.properties.kind:constrain(item)]))
  return value
 }
 return constrain(schema)
}
/** A bounded prose repair can reference only already validated, scored domains. */
export function mmiHighlightsSchemaFor(feedback:MMIFeedback){
 const scored=feedback.domains.filter(d=>d.status==='scored')
 const variants=scored.map(d=>object({domain:enumeration([d.key]),text:{...str,minLength:1},references:{...evidenceRefs,items:enumeration([...new Set(d.evidence.flatMap(e=>e.references))])}}))
 const highlights=variants.length?list({anyOf:variants},5):list(object({domain:key,text:str,references:evidenceRefs}),0)
 return object({strengths:highlights,priorities:highlights})
}
const auditSchema=(referenceSchema:unknown)=>object({format_version:enumeration(['mmi-audit-v2']),warnings:list(object({category:enumeration(['quotation','attribution','omission','expectations','scoring','overlap','concern','fairness','summary','uncertainty']),domain:{anyOf:[key,{type:'null'}]},references:referenceSchema,detail:str}),30),requires_human_attention:{type:'boolean'}})
export const MMI_AUDIT_SCHEMA=auditSchema(refs)
/** Constrain generated audit citations to this report's actual evidence IDs. */
export function mmiAuditSchemaFor(feedback:MMIFeedback){
 const ids=[...new Set(mmiReferences(feedback).map(r=>r.id))]
 return auditSchema(ids.length?list(enumeration(ids),30):list({type:'string'},0))
}
export function isMMIFeedback(value:unknown):value is MMIFeedback{return !!value&&typeof value==='object'&&'format_version' in value&&value.format_version===MMI_FEEDBACK_VERSION}
export function mmiBand(score:number){return MMI_BANDS[Math.max(0,Math.min(6,Math.floor(score+.5)-1))]}
export function validateMMISpecification(value:unknown):MMISpecification{
 if(!validateSchema(value,MMI_SPEC_SCHEMA))throw new Error('invalid_mmi_specification')
 const s=value as MMISpecification
 if(!s.task.trim()||!s.role.trim()||!s.primary_domains.length||new Set(s.primary_domains.map(d=>d.key)).size!==s.primary_domains.length||s.primary_domains.some(d=>!d.reason.trim()))throw new Error('invalid_mmi_specification')
 return s
}
export function hasMMIExercise(text:string){return /\b(?:timed (?:practice|rehearsal|exercise)|(?:practise|practice|rehearse|record|repeat) (?:this|your|the|again|an?\b).{0,60}(?:answer|response|station|seconds|minutes)|(?:practice|rehearsal) (?:task|exercise|drill)|\d+[- ](?:second|minute) (?:drill|answer|exercise))\b/i.test(text)}
export function mmiReferences(f:MMIFeedback):MMIReference[]{return [...f.source.references,...f.reviewer_evidence.map(r=>({id:r.id,speaker:r.speaker,text:r.text,start:null,end:null,timestamp:r.timestamp,label_origin:'added' as const}))]}
function evidenceValid(e:MMIEvidence,source:MMISource){
 const found=e.references.map(id=>source.references.find(r=>r.id===id))
 if(!e.text.trim()||!found.length||found.some(r=>!r))throw new Error('invalid_mmi_evidence_reference')
 if(e.kind==='quote'&&!found.some(r=>r!.speaker===e.speaker&&r!.text.includes(e.text)))throw new Error('invalid_mmi_quotation')
 if(e.kind==='paraphrase'&&!found.some(r=>r!.speaker===e.speaker))throw new Error('invalid_mmi_attribution')
 const confirmedNoAnswer=source.response_disposition==='not_answered'&&found.some(r=>r!.speaker==='recording_note')
 if(e.kind==='omission'&&(source.completeness!=='complete'||!found.some(r=>r!.speaker==='interviewer'||r!.speaker==='prompt')||(!found.some(r=>r!.speaker==='candidate')&&!confirmedNoAnswer)))throw new Error('invalid_mmi_omission')
}
/** JSONB reorders object keys; compare content while preserving evidence-array order. */
function canonicalJSON(value:unknown):unknown{
 if(Array.isArray(value))return value.map(canonicalJSON)
 if(value!==null&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonicalJSON(item)]))
 return value
}
function sameJSON(a:unknown,b:unknown){return JSON.stringify(canonicalJSON(a))===JSON.stringify(canonicalJSON(b))}
export function validateMMIFeedback(value:unknown,options:{draft?:boolean;source?:MMISource;stationId?:string;specification?:MMISpecification;durationSeconds?:number}={}):MMIFeedback{
 if(!isMMIFeedback(value)||value.rubric_version!==MMI_RUBRIC_VERSION||value.format!=='mmi'||typeof value.station_id!=='string'||!value.station_id)throw new Error('invalid_mmi_version')
 const allowed=['format_version','rubric_version','format','station_id','specification','source','reviewer_evidence','reviewer_scope',...Object.keys(MMI_MARK_SCHEMA.properties)]
 if(Object.keys(value).some(k=>!allowed.includes(k)))throw new Error('invalid_mmi_fields')
 const mark=Object.fromEntries(Object.keys(MMI_MARK_SCHEMA.properties).map(k=>[k,value[k as keyof MMIFeedback]]))
 if(!validateSchema(mark,MMI_MARK_SCHEMA))throw new Error('invalid_mmi_feedback')
 validateMMISpecification(value.specification)
 const source=value.source
 if(!source||source.media_assessed!=='transcript'||!['complete','partial','unknown'].includes(source.completeness)||!['full','excerpt','unknown'].includes(source.primary_task_coverage)||(source.response_disposition!==undefined&&!['insubstantial','not_answered'].includes(source.response_disposition))||!Array.isArray(source.limitations)||!source.limitations.every(s=>typeof s==='string')||!Array.isArray(source.references)||source.references.length>1000||source.references.some(r=>!r||typeof r.id!=='string'||typeof r.text!=='string'||r.text.length>100000||!['candidate','interviewer','actor','recording_note','unknown','prompt'].includes(r.speaker))||new Set(source.references.map(r=>r.id)).size!==source.references.length)throw new Error('invalid_mmi_source')
 if(options.source&&!sameJSON(options.source,source))throw new Error('mmi_source_changed')
 if(options.stationId&&options.stationId!==value.station_id)throw new Error('invalid_mmi_station')
 if(options.specification&&!sameJSON(options.specification,value.specification))throw new Error('mmi_specification_changed')
 const scope=value.reviewer_scope
 if(!scope||!['none','audio','video'].includes(scope.media_inspected)||!['complete','partial','unknown'].includes(scope.completeness)||!['full','excerpt','unknown'].includes(scope.primary_task_coverage)||!Array.isArray(value.reviewer_evidence)||value.reviewer_evidence.length>50)throw new Error('invalid_mmi_reviewer_evidence')
 for(const r of value.reviewer_evidence){
  if(!r||!/^R[\w-]{1,70}$/.test(r.id)||typeof r.text!=='string'||r.text.length>6000||(!options.draft&&!r.text.trim())||!['candidate','interviewer','actor','recording_note','unknown'].includes(r.speaker)||!['observation','transcript_correction'].includes(r.kind)||r.media!==scope.media_inspected)throw new Error('invalid_mmi_reviewer_evidence')
  if(r.timestamp!==null){const m=/^(\d{1,2}):([0-5]\d)$/.exec(r.timestamp);if(!m||Number(m[1])*60+Number(m[2])>(options.durationSeconds??490))throw new Error('invalid_mmi_reviewer_timestamp')}
 }
 if(new Set(value.reviewer_evidence.map(r=>r.id)).size!==value.reviewer_evidence.length)throw new Error('invalid_mmi_reviewer_evidence')
 const combinedSource={...source,references:mmiReferences(value),completeness:value.reviewer_evidence.length&&scope.completeness==='complete'?'complete' as const:source.completeness}
 const selected=new Set(value.specification.primary_domains.map(d=>d.key))
 if(new Set(value.domains.map(d=>d.key)).size!==value.domains.length||[...selected].some(key=>!value.domains.some(d=>d.key===key)))throw new Error('invalid_mmi_domains')
 for(const d of value.domains){
  if((d.status==='scored')!==(d.score!==null)||((d.status!=='not_applicable')!==selected.has(d.key)))throw new Error('invalid_mmi_domain_status')
  d.evidence.forEach(e=>{evidenceValid(e,combinedSource);if(e.kind==='quote'&&e.references.some(id=>value.reviewer_evidence.some(r=>r.id===id&&r.kind==='observation')))throw new Error('mmi_observation_is_not_verbatim')})
  if(d.status==='scored'&&!d.evidence.some(e=>e.speaker==='candidate'||e.kind==='omission'))throw new Error('mmi_candidate_evidence_required')
  if(!options.draft&&(!d.rationale.trim()||(d.status==='scored'?!d.improvement.trim():d.status==='insufficient_evidence'?!d.needed_evidence.trim():false)))throw new Error('incomplete_mmi_domain')
  if(d.status!=='scored'&&d.improvement.trim())throw new Error('mmi_unseen_performance_advice')
 }
 if((value.global.status==='scored')!==(value.global.score!==null)||(!options.draft&&!value.global.reason.trim()))throw new Error('invalid_mmi_global')
 if(value.global.score!==null&&((source.primary_task_coverage==='excerpt'&&!(value.reviewer_evidence.length&&scope.primary_task_coverage==='full'))||!value.domains.some(d=>d.status==='scored')))throw new Error('mmi_global_insufficient_evidence')
 for(const h of [...value.strengths,...value.priorities]){
  if(!value.domains.some(d=>d.key===h.domain&&d.status==='scored'))throw new Error('invalid_mmi_highlight_unscored_domain')
  if(!h.references.length||h.references.some(id=>!combinedSource.references.some(r=>r.id===id)))throw new Error('invalid_mmi_highlight_reference')
  if(!options.draft&&!h.text.trim())throw new Error('invalid_mmi_highlight_text')
 }
 if(new Set(value.concerns.map(c=>c.id)).size!==value.concerns.length)throw new Error('invalid_mmi_concerns')
 for(const c of value.concerns){
  c.evidence.forEach(e=>{evidenceValid(e,combinedSource);if(e.kind==='quote'&&e.references.some(id=>value.reviewer_evidence.some(r=>r.id===id&&r.kind==='observation')))throw new Error('mmi_observation_is_not_verbatim')})
  if(!c.evidence.length||!c.id.trim()||(!options.draft&&(!c.description.trim()||!c.consequence.trim())))throw new Error('invalid_mmi_concern')
  if(c.status!=='clarification_needed'&&(c.certainty!=='clear'||!c.evidence.some(e=>e.kind!=='omission'&&e.speaker==='candidate')||(c.evidence.some(e=>e.references.some(id=>/\[(?:unclear|inaudible)/i.test(source.references.find(r=>r.id===id)?.text??'')))&&!c.evidence.some(e=>e.references.some(id=>value.reviewer_evidence.some(r=>r.id===id&&r.kind==='transcript_correction'))))))throw new Error('mmi_uncertain_concern')
 }
 if(!options.draft&&(!value.closing.verdict.trim()||!value.closing.successful_improvement.trim()))throw new Error('incomplete_mmi_closing')
 const advice=[...value.domains.map(d=>d.improvement),...value.priorities.map(h=>h.text),value.closing.verdict,value.closing.successful_improvement].join(' ')
 if(hasMMIExercise(advice))throw new Error('mmi_exercises_not_allowed')
 if(/\n\s*\n/.test(value.closing.verdict+value.closing.successful_improvement))throw new Error('mmi_closing_must_be_concise')
 return value
}
export function makeMMIFeedback(stationId:string,source:MMISource,specification:MMISpecification,mark:unknown):MMIFeedback{
 if(!validateSchema(mark,MMI_MARK_SCHEMA))throw new Error('invalid_mmi_feedback')
 const value={...(mark as object),reviewer_evidence:[],reviewer_scope:{media_inspected:'none',completeness:'unknown',primary_task_coverage:'unknown'},format_version:MMI_FEEDBACK_VERSION,rubric_version:MMI_RUBRIC_VERSION,format:'mmi',station_id:stationId,source,specification}
 return validateMMIFeedback(value,{source,stationId,specification})
}
export function manualMMIFeedback(stationId:string,source:MMISource,spec?:MMISpecification):MMIFeedback{
 const specification=spec??{task:'Review the saved station prompt before selecting its assessed domains.',role:'Prospective medical student',basis:'provisional',primary_domains:[{key:'communication_rapport',reason:'Verbal explanation requested.'},{key:'content_reasoning',reason:'Answer the saved task with a relevant rationale.'}],essential_expectations:[],optional_enrichment:[],acceptable_approaches:[],interaction_conditions:'Confirm from the saved station.',limitations:['Provisional specification requires reviewer confirmation.']} satisfies MMISpecification
 return {reviewer_evidence:[],reviewer_scope:{media_inspected:'none',completeness:'unknown',primary_task_coverage:'unknown'},format_version:MMI_FEEDBACK_VERSION,rubric_version:MMI_RUBRIC_VERSION,format:'mmi',station_id:stationId,source,specification,domains:specification.primary_domains.map(d=>({key:d.key,status:'insufficient_evidence',score:null,evidence:[],rationale:'',improvement:'',needed_evidence:''})),global:{status:'insufficient_evidence',score:null,reason:''},strengths:[],priorities:[],concerns:[],closing:{verdict:'',successful_improvement:''}}
}
export function validateMMIAudit(value:unknown,feedback:MMIFeedback):MMIAudit{
 if(!validateSchema(value,MMI_AUDIT_SCHEMA))throw new Error('invalid_mmi_audit')
 const a=value as MMIAudit
 if(a.warnings.some(w=>!w.detail.trim()||w.references.some(id=>!mmiReferences(feedback).some(r=>r.id===id)))||a.warnings.length&&!a.requires_human_attention)throw new Error('invalid_mmi_audit_evidence')
 return a
}
