// Fixed, versioned selection shared by all trial accounts.
export const TRIAL_CATALOG_VERSION = 'interview-trial-v1'
export const TRIAL_MMI_IDS: readonly string[] = [
  "mmi-confidentiality-patient-safety",
  "mmi-team-disagreement",
  "mmi-honest-feedback",
  "mmi-access-support",
  "mmi-resource-choice",
  "mmi-owning-error",
  "mmi-listening-concern",
  "mmi-managing-pressure",
  "mmi-using-an-interpreter",
  "mmi-health-misinformation",
  "mmi-fatigued-colleague",
  "mmi-disability-and-access",
  "mmi-conflict-of-interest",
  "mmi-young-person-seeking-help",
  "mmi-telehealth-privacy"
]
export const TRIAL_PANEL_IDS: readonly string[] = [
  "panel-motivation",
  "panel-service",
  "panel-resilience",
  "panel-teamwork",
  "panel-patient-centred-care",
  "panel-communication-listening",
  "panel-ethics-judgement",
  "panel-integrity",
  "panel-self-awareness-values",
  "panel-feedback",
  "panel-leadership-initiative",
  "panel-adaptability-change",
  "panel-conflict-resolution",
  "panel-accountability-professionalism",
  "panel-cultural-safety",
  "panel-aboriginal-torres-strait-islander-health",
  "panel-diversity-inclusion",
  "panel-health-equity-access",
  "panel-rural-remote-health",
  "panel-social-determinants",
  "panel-public-health-prevention",
  "panel-health-system",
  "panel-evidence-critical-thinking",
  "panel-research-curiosity",
  "panel-technology-ai",
  "panel-privacy-confidentiality",
  "panel-patient-advocacy",
  "panel-team-communication",
  "panel-work-life-sustainable-practice",
  "panel-learning-from-failure",
  "panel-motivation-service",
  "panel-community-engagement"
]
export function trialQuestionAllowed(id: string, questionIndex = 0) { return questionIndex === 0 && (TRIAL_MMI_IDS.includes(id) || TRIAL_PANEL_IDS.includes(id)) }
