import Link from 'next/link'
import { interviewQueue } from '@/lib/interviews/marking-data'
import { statusLabel } from '@/lib/interviews/video-validation'
export const dynamic='force-dynamic'
export const metadata={title:'Admin · Mock Interview reviews'}
export default async function Page({searchParams}:{searchParams:Promise<{format?:string;status?:string;page?:string}>}){
 const filters=await searchParams
 const {items,jobs,error,sampledAt,oldestAt,counts,total,page}=await interviewQueue({...filters,page:Number(filters.page)||0})
 const visible=items
 return <main className="mx-auto max-w-6xl space-y-6 px-5 py-10"><Link href="/admin">← Admin dashboard</Link><h1 className="font-display text-4xl font-semibold">Mock Interview reviews</h1>
 {error?<p role="alert">The queue is unavailable. Apply migration 0033 and check server configuration.</p>:<>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Submissions waiting" value={counts.waiting}/><Metric label="Jobs waiting" value={counts.queued}/><Metric label="Jobs retrying" value={counts.retrying}/><Metric label="Dead jobs" value={counts.dead}/></div><p className="text-sm text-muted">Oldest waiting: {Math.floor((sampledAt-oldestAt)/3600000)} hours · {counts.refunded} ungradable / refunded · {counts.ready} awaiting review. Oldest ready submissions appear first.</p>
 <form className="flex flex-wrap items-end gap-3"><label>Format<select name="format" defaultValue={filters.format??''} className="ml-2 rounded-full border px-4 py-3"><option value="">All</option><option value="mmi">MMI</option><option value="panel">Panel</option></select></label><label>Status<select name="status" defaultValue={filters.status??''} className="ml-2 rounded-full border px-4 py-3"><option value="">Active submissions</option>{['queued','processing','awaiting_review','in_review','needs_attention','released','ungradable'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><button className="rounded-full bg-brand px-5 py-3 text-brand-foreground">Filter</button></form>
 <div className="space-y-4">{visible.map(({attempt:a,student,marking,jobs:attemptJobs})=><article key={a.id} className="rounded-2xl border border-border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-muted">{student} · {a.format.toUpperCase()} · {Math.floor(a.duration_seconds/60)}:{String(a.duration_seconds%60).padStart(2,'0')}</p><h2 className="mt-1 font-display text-xl font-semibold"><Link href={`/admin/interviews/${a.id}`}>{a.station_title} →</Link></h2></div><p className="text-sm">{statusLabel(a)}</p></div><p className="mt-2 text-sm text-muted">Submitted {new Date(a.submitted_for_marking_at??a.created_at).toLocaleString('en-AU')} · {Math.floor((sampledAt-Date.parse(a.submitted_for_marking_at??a.created_at))/3600000)}h in queue · Transcript: {a.transcription_status} · {marking?.draft_feedback?'Draft available':'No draft yet'}</p><QueueFlags assessment={marking?.ai_assessment} audit={marking?.evidence_audit}/>{attemptJobs.length>0&&<p className="mt-2 text-sm">Processing: {attemptJobs.map(j=>`${j.job_type} ${j.status} (${j.attempt_count} attempts)`).join(' · ')}</p>}</article>)}{!visible.length&&<p>No submissions match these filters.</p>}</div>
 <nav aria-label="Queue pages" className="flex gap-4">{page>0&&<Link href={`?${new URLSearchParams({format:filters.format??'',status:filters.status??'',page:String(page-1)})}`}>Previous page</Link>}{(page+1)*100<total&&<Link href={`?${new URLSearchParams({format:filters.format??'',status:filters.status??'',page:String(page+1)})}`}>Next page</Link>}</nav>
 <details className="rounded-2xl border p-4"><summary>Processing operations, including self-review transcripts</summary><p className="mt-2 text-sm text-muted">Counts above cover all jobs. This list shows up to 1,000 outstanding jobs; use the runbook to recover a cleanup job. Cancelled AI jobs after human review are also recorded as dead.</p><ul className="mt-3 space-y-2 text-sm">{jobs.filter(j=>j.status==='dead'||j.status==='failed').map((j,i)=><li key={i}><span className="font-mono">{j.attempt_id}</span> · {j.job_type} · {j.status} · attempt {j.attempt_count}</li>)}</ul></details>
 </>}
 </main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-surface p-4"><p className="font-mono text-2xl">{value}</p><p className="text-sm text-muted">{label}</p></div>}
function QueueFlags({assessment,audit}:{assessment:unknown;audit:unknown}){
 const a=assessment as {flags?:string[];observations?:Array<{confidence:string}>}|null,u=audit as {requires_human_attention?:boolean;warnings?:Array<{category:string}>}|null
 return <p className="mt-2 text-sm">{a?.observations?.some(o=>o.confidence==='low')?'Low-confidence evidence · ':''}{a?.flags?.join(' · ')}{u?.requires_human_attention?' · Audit requires human attention':''}{u?.warnings?.map(w=>` · ${w.category.replaceAll('_',' ')}`)}</p>
}
