'use client'
import { useState } from 'react'
import { formatQuestionTime } from '@/lib/mock/review'
import type { PaidReport } from '@/lib/mock/report/types'
import styles from './report.module.css'
import mapStyles from './learning-insights.module.css'
export function TimePressureMap({data,onQuestion}:{data:PaidReport['timePressure'];onQuestion:(id:string)=>void}){
 const [section,setSection]=useState(data[0]?.section??''),[window,setWindow]=useState('five')
 const current=data.find(s=>s.section===section)??data[0],period=current?.windows.find(w=>w.key===window)
 if(!current||!period)return <p>Complete a mock to see your time-pressure map.</p>
 const before=period.earlyAccuracy,after=period.lateAccuracy
 const insight=before==null||after==null?'There are not enough timed answers in both periods to compare accuracy.':`${current.name} accuracy ${after<before?'falls':after>before?'rises':'stays level'} ${after===before?`at ${after}%`:`from ${before}% to ${after}%`} ${window==='five'?'when less than five minutes remain':window==='six'?'in the final six minutes':'in the final 20% of the time allowance'}.`
 return <section className={styles.panel} data-tone="timing"><h2>Time-pressure map</h2><p className={styles.note}>Accuracy means percentage of available marks on the timed answers in each group. A pattern under pressure does not prove that time caused an error.</p><div className={styles.tabs} aria-label="Time-pressure subtest">{data.map(s=><button key={s.section} aria-pressed={s.section===current.section} onClick={()=>setSection(s.section)}>{s.name}</button>)}</div><div className={styles.tabs} aria-label="Pressure period">{current.windows.map(w=><button key={w.key} aria-pressed={w.key===window} onClick={()=>setWindow(w.key)}>{w.label}</button>)}</div>
 <p className={mapStyles.insight}>{insight}</p>{period.smallSample&&<p className={styles.note}>Small sample: {period.earlyCount} earlier answers and {period.lateCount} late answers. Treat the comparison cautiously.</p>}
 <div className={styles.metrics}><div><strong>{period.completed}</strong><span>First completed under pressure</span></div><div><strong>{period.lateCount}</strong><span>Final answers under pressure</span></div><div><strong>{period.marksLost}/{period.maximum}</strong><span>Marks missed on late answers</span></div><div><strong>{current.unansweredMarks}</strong><span>Unanswered marks at finish</span></div></div>
 <p className={styles.note}>First completion is separate from a later answer change. Unanswered marks are shown separately because their cause and timing are not known.{current.missingTiming>0?` ${current.missingTiming} answers have no recorded decision time.`:''}{current.missingCompletionTiming>0?` First-completion timing is unavailable for ${current.missingCompletionTiming} answers.`:''}</p>
 <div className={mapStyles.legend}><span>Green: correct</span><span>Rose: incorrect</span><span>Purple: partial</span><span>Grey: unanswered</span><span>Outlined: final answer under pressure</span></div><nav className={mapStyles.map} aria-label={`${current.name} question pressure map`}>{current.questions.map(q=><button key={q.id} data-status={q.status} data-late={period.ids.includes(q.id)} onClick={()=>onQuestion(q.id)} title={`Question ${q.number}: ${q.status}${q.at==null?'':`, ${formatQuestionTime(current.budget-q.at)} remaining`}`} aria-label={`Review question ${q.number}, ${q.status}${period.ids.includes(q.id)?', under pressure':''}`}>{q.number}</button>)}</nav>
 <h3>Average time by question type</h3><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Type</th><th>Average time</th><th>Recommended starting pace</th></tr></thead><tbody>{current.types.map(t=><tr key={t.name}><td>{t.name}<small>{t.answered} answered / {t.count} questions</small></td><td>{t.averageSeconds==null?'—':formatQuestionTime(t.averageSeconds)}</td><td>{formatQuestionTime(t.recommendedSeconds)}</td></tr>)}</tbody></table></div><p className={styles.note}>Starting pace = section allowance ÷ question count. It is a planning guide, not a measured question-type benchmark. Reading a shared passage can make the first question slower; use the set’s average as well.</p>
 </section>
}
export function ErrorTotals({data}:{data:PaidReport['errors']}){
 const leading=[...data.rows].sort((a,b)=>b.marks-a.marks)[0]
 return <section className={styles.panel} data-tone="attention"><h2>Your error classifications</h2>{data.labelledErrors?<p className={mapStyles.insight}>You labelled {leading.marks} missed mark{leading.marks===1?'':'s'} “{leading.category}” across your last {data.mocks} mock{data.mocks===1?'':'s'}.</p>:<p>Open a missed question, read its explanation and choose the main reason for your error. Your totals will appear here.</p>}<p className={styles.note}>One student-selected reason per error. These totals describe the missed marks you labelled, not independently diagnosed causes. {data.unclassifiedErrors} errors are still unclassified.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Main reason</th><th>Questions</th><th>Marks not earned</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.category}><td>{r.category}</td><td>{r.count}</td><td>{r.marks}</td></tr>)}</tbody></table></div></section>
}
export function ConfidenceCalibration({data,onQuestion}:{data:PaidReport['confidence'];onQuestion:(id:string)=>void}){
 return <section className={styles.panel} data-tone="progress"><h2>Confidence calibration</h2><p>{data.recorded} questions have pre-marking confidence recorded; {data.unrecorded} do not.</p><p className={styles.note}>Confidence is optional. A confident error can suggest a misconception; a confident correct answer is a mastery signal, not proof of lasting mastery. Partial-credit answers appear in “not fully correct”.</p>{data.groups.map(g=><div key={g.key} className={mapStyles.calibration}><div><strong>{g.label}</strong><p>{g.guidance}</p></div><b>{g.count}</b>{g.ids.length>0&&<button className={styles.button} onClick={()=>onQuestion(g.ids[0])}>Review {g.count===1?'question':'questions'}</button>}</div>)}{data.recorded===0&&<p className={styles.note}>Record confidence while answering your next mock. Past confidence cannot be inferred from answer accuracy.</p>}</section>
}
