'use client'
import Link from 'next/link'
import { percentileBand } from '../percentile-bands'
import type { PaidReport } from '@/lib/mock/report/types'
import { percentileLabel, estimateAnzPercentile } from '@/lib/ucat/benchmarks'
import { formatQuestionTime } from '@/lib/mock/review'
import styles from './report.module.css'
type Data=PaidReport['postMortem']
const point=(v:number)=>`${v>0?'+':''}${v}`
export function MarksOpportunity({data,onQuestion}:{data:Data;onQuestion:(id:string)=>void}){
 const o=data.opportunities
 return <section className={styles.panel} data-tone="attention"><h2>Marks left on the table</h2><div className={styles.metrics}><div><strong>{o.total}</strong><span>Missed marks in priority areas</span></div><div><strong>{o.estimated==null?'—':`+${o.estimated}`}</strong><span>History-based practice target</span></div></div><p>Start with these opportunities. Each missed mark appears in one row only.</p><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Opportunity</th><th>Missed marks</th><th>Estimated additional marks</th><th>Review</th></tr></thead><tbody>{o.rows.map(r=><tr key={r.key}><td>{r.label}<small>{r.ids.length} questions</small></td><td>{r.marks}</td><td>{r.estimated==null?'Not enough history':`+${r.estimated}`}<small>{r.covered} of {r.ids.length} questions estimated</small></td><td>{r.ids.length>0&&<button className={styles.button} onClick={()=>onQuestion(r.ids[0])}>Start review</button>}</td></tr>)}</tbody></table></div><p className={styles.note}>{o.other} other missed marks sit outside these priority areas. Overlapping questions are counted as unattempted first, then easy, slow and repeated errors.</p><details><summary>How the estimate works</summary><p className={styles.note}>The target uses your mark rate on at least five distinct earlier answered questions of the same subtest, type and recorded difficulty. It excludes questions in this mock and repeated copies. For each eligible question, expected marks minus marks already earned gives an estimated additional amount, capped at the missed marks. These are practice targets, not guaranteed gains or extra marks awarded to this attempt.</p><p className={styles.note}>{o.covered} of {o.count} priority questions have enough comparable history. Unestimated questions are excluded from the target. A slow answer means over 1.5 times the section’s equal-share pace. A repeated reason must be student-labelled in this mock and another of the last five mocks. Difficulty comes from the question bank; missing labels are not guessed.</p></details></section>
}
export function MockPostMortem({data,examSlug,onQuestion}:{data:Data;examSlug:string;onQuestion:(id:string)=>void}){
 const score=data.scores.totalScore
 return <><section className={styles.panel} data-tone="score"><h2>Your mock post-mortem</h2><p>What went well, where marks were missed, and what to do next.</p><div className={styles.metrics}><div><strong>{score??'—'}</strong><span>Estimated cognitive score / 2700</span></div><div data-percentile-band={percentileBand(data.scores.percentile)}><strong>{data.scores.percentile?percentileLabel(data.scores.percentile):'See subtest scores'}</strong><span>Estimated ANZ percentile · SJT separate</span></div></div><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Subtest</th><th>Marks</th><th>Estimated score</th><th>Estimated percentile</th></tr></thead><tbody>{data.scores.sections.map(s=>{const section=data.sections.find(v=>v.slug===s.slug);return <tr key={s.slug}><td>{data.timing.find(t=>t.section===s.slug)?.name??s.slug}</td><td>{section?`${section.raw}/${section.maximum}`:'See section review'}</td><td>{s.scaled??'—'} / 900</td><td data-percentile-band={percentileBand(s.scaled==null?null:estimateAnzPercentile(s.slug,s.scaled))}>{s.scaled!=null&&estimateAnzPercentile(s.slug,s.scaled)?percentileLabel(estimateAnzPercentile(s.slug,s.scaled)!):'—'}</td></tr>})}</tbody></table></div></section>
 <div className={styles.split}><section className={styles.panel} data-tone="progress"><h2>Best-performing section</h2>{data.best.map(s=><p key={s.slug}><strong>{s.name}</strong> · {Math.round(s.accuracy)}% of marks ({s.raw}/{s.maximum})</p>)}<p className={styles.note}>Compared by percentage of available marks. Ties are shown.</p></section><section className={styles.panel} data-tone="attention"><h2>Largest score opportunity</h2>{data.largest.length?data.largest.map(s=><div key={s.slug}><p><strong>{s.name}</strong> · {s.lost} marks missed ({Math.round(100-s.accuracy)}% of its marks)</p><button className={styles.button} onClick={()=>onQuestion(s.ids[0])}>Review section errors</button></div>):<p>Full marks in every section. Consolidate with fresh questions.</p>}<p className={styles.note}>Ranked by the proportion of marks missed, so sections of different sizes can be compared. This is raw-mark headroom, not a predicted scaled-score gain.</p></section></div>
 <section className={styles.panel} data-tone="timing"><h2>Time-management failure points</h2><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Subtest</th><th>Slow questions</th><th>Final five minutes</th><th>Unattempted</th></tr></thead><tbody>{data.timing.map(t=><tr key={t.section}><td>{t.name}</td><td>{t.slowCount}<small>{formatQuestionTime(t.excessSeconds)} above equal-share pace{t.ids.length>0&&<> · <button className={styles.button} onClick={()=>onQuestion(t.ids[0])}>Review</button></>}</small></td><td>{t.lateLost} marks missed<small>{t.earlyAccuracy==null||t.lateAccuracy==null?'Not enough timed answers to compare':`${t.earlyAccuracy}% → ${t.lateAccuracy}% of marks`} · {t.lateCount} late answers{t.missingTiming>0?` · ${t.missingTiming} answers lack timing`:''}</small></td><td>{t.unanswered}</td></tr>)}</tbody></table></div><p className={styles.note}>These are points to investigate, not proof that time caused an error. Shared passages can make the first question slower. Use set averages when reviewing.</p></section>
 <div className={styles.split}><section className={styles.panel} data-tone="attention"><h2>Easy questions missed</h2><p><strong>{data.easy.marks} marks</strong> across {data.easy.ids.length} questions labelled easy in the bank.</p>{data.easy.ids.length>0&&<button className={styles.button} onClick={()=>onQuestion(data.easy.ids[0])}>Review easy questions</button>}{data.easy.unknownDifficulty>0&&<p className={styles.note}>{data.easy.unknownDifficulty} questions have no saved difficulty label and are excluded.</p>}</section><section className={styles.panel} data-tone="attention"><h2>Categories with the most lost marks</h2>{data.types.slice(0,3).map(t=><button key={`${t.section}:${t.name}`} className={styles.queue} onClick={()=>onQuestion(t.ids[0])}><span>{t.name}<small>{t.sectionName}</small></span><strong>{t.marks} marks →</strong></button>)}{!data.types.length&&<p>No marks missed.</p>}{data.reasons.length>0?<p className={styles.note}>Your leading labelled reason: {data.reasons[0].category} · {data.reasons[0].marks} marks in this mock{data.reasons[0].repeated?' · also labelled in an earlier mock':''}.</p>:<p className={styles.note}>Classify your errors after reading the explanations to identify recurring reasons.</p>}</section></div>
 <section className={styles.panel} data-tone="action"><h2>Three follow-up sessions</h2><ol className={styles.days}>{data.sessions.map((s,i)=><li key={i}><span>{i+1}</span><div><strong>{s.title}</strong><p>{s.detail}</p>{s.ids.length>0&&<button className={styles.button} onClick={()=>onQuestion(s.ids[0])}>Review target questions</button>} <Link className={styles.button} href={`/practice/${encodeURIComponent(examSlug)}/${encodeURIComponent(s.section)}`}>Choose fresh practice</Link></div><small>{s.minutes} min</small></li>)}</ol></section>
 <section className={styles.panel} data-tone="progress"><h2>Compared with your previous mock</h2>{data.comparison?<><p>{data.comparison.label} · {new Date(data.comparison.completedAt).toLocaleDateString('en-AU')} · {data.comparison.sameForm?'Same form':'Different form'}</p><p><strong>{data.comparison.delta==null?'No comparable cognitive total':`${point(data.comparison.delta)} estimated points`}</strong>{data.comparison.delta!=null&&<> · {data.comparison.score} → {score}</>}</p>{data.comparison.sections.map(s=><p key={s.name}>{s.name}: {s.delta==null?'No comparable score':`${point(s.delta)} points`}</p>)}<p className={styles.note}>This compares the immediately previous completed mock. Different forms vary in difficulty; repeated forms can benefit from familiarity.</p></>:<p>Complete another mock to unlock a comparison with this attempt. No earlier completed mock is available.</p>}</section><MarksOpportunity data={data} onQuestion={onQuestion}/></>
}
