begin;
create table public.interview_story_prompts (
 id text primary key,
 category text not null,
 prompt text not null
);
alter table public.interview_story_prompts enable row level security;
create policy "Read story prompts" on public.interview_story_prompts for select to authenticated using(true);
revoke all on public.interview_story_prompts from public,anon,authenticated;
grant select on public.interview_story_prompts to authenticated;
grant all on public.interview_story_prompts to service_role;
insert into public.interview_story_prompts(id,category,prompt) values
('community-and-service-01','community-and-service','A time you volunteered in your community.'),
('community-and-service-02','community-and-service','A time you supported someone experiencing disadvantage.'),
('community-and-service-03','community-and-service','A time you worked with people from a different background.'),
('community-and-service-04','community-and-service','A time you contributed without receiving recognition.'),
('community-and-service-05','community-and-service','A time you learnt something from the community you were serving.'),
('community-and-service-06','community-and-service','A time you noticed that a service was not meeting people’s needs.'),
('community-and-service-07','community-and-service','A time you helped improve a community activity or organisation.'),
('community-and-service-08','community-and-service','A time you had to listen before deciding how to help.'),
('teamwork-01','teamwork','A time you worked successfully in a team.'),
('teamwork-02','teamwork','A time your team faced a disagreement.'),
('teamwork-03','teamwork','A time you helped a team recover from a setback.'),
('teamwork-04','teamwork','A time you supported a struggling team member.'),
('teamwork-05','teamwork','A time you had to compromise.'),
('teamwork-06','teamwork','A time you worked with someone whose style differed from yours.'),
('teamwork-07','teamwork','A time you helped a quieter person contribute.'),
('teamwork-08','teamwork','A time poor communication affected a team outcome.'),
('teamwork-09','teamwork','A time you had to take responsibility for a team mistake.'),
('leadership-and-initiative-01','leadership-and-initiative','A time you led a group or project.'),
('leadership-and-initiative-02','leadership-and-initiative','A time you took initiative without being asked.'),
('leadership-and-initiative-03','leadership-and-initiative','A time you motivated others.'),
('leadership-and-initiative-04','leadership-and-initiative','A time you had to lead without formal authority.'),
('leadership-and-initiative-05','leadership-and-initiative','A time your leadership approach changed.'),
('leadership-and-initiative-06','leadership-and-initiative','A time you delegated responsibilities.'),
('leadership-and-initiative-07','leadership-and-initiative','A time you made an unpopular but necessary decision.'),
('leadership-and-initiative-08','leadership-and-initiative','A time you identified a problem and proposed a solution.'),
('leadership-and-initiative-09','leadership-and-initiative','A time you learnt from a leadership failure.'),
('communication-01','communication','A time you explained a complex idea simply.'),
('communication-02','communication','A time you adapted your communication for someone else.'),
('communication-03','communication','A time you had a difficult conversation.'),
('communication-04','communication','A time you resolved a misunderstanding.'),
('communication-05','communication','A time you listened to someone who was distressed.'),
('communication-06','communication','A time you received unexpected information.'),
('communication-07','communication','A time you communicated across a language or cultural barrier.'),
('communication-08','communication','A time written or digital communication caused confusion.'),
('communication-09','communication','A time you had to communicate under pressure.'),
('empathy-and-support-01','empathy-and-support','A time you supported someone emotionally.'),
('empathy-and-support-02','empathy-and-support','A time you noticed that someone was struggling.'),
('empathy-and-support-03','empathy-and-support','A time you changed your assumptions about another person.'),
('empathy-and-support-04','empathy-and-support','A time you helped someone feel included or respected.'),
('empathy-and-support-05','empathy-and-support','A time you had to be patient with someone.'),
('empathy-and-support-06','empathy-and-support','A time you supported someone without trying to “fix” everything.'),
('empathy-and-support-07','empathy-and-support','A time you recognised that another person’s circumstances affected their behaviour.'),
('empathy-and-support-08','empathy-and-support','A time you had to balance empathy with boundaries.'),
('challenges-and-resilience-01','challenges-and-resilience','A significant setback you experienced.'),
('challenges-and-resilience-02','challenges-and-resilience','A time you failed to meet your own expectations.'),
('challenges-and-resilience-03','challenges-and-resilience','A time you persevered with something difficult.'),
('challenges-and-resilience-04','challenges-and-resilience','A time you had to manage competing priorities.'),
('challenges-and-resilience-05','challenges-and-resilience','A time you coped with uncertainty.'),
('challenges-and-resilience-06','challenges-and-resilience','A time you recovered from disappointment.'),
('challenges-and-resilience-07','challenges-and-resilience','A time your usual strategy stopped working.'),
('challenges-and-resilience-08','challenges-and-resilience','A time you asked for help.'),
('challenges-and-resilience-09','challenges-and-resilience','A time you supported someone else through difficulty.'),
('challenges-and-resilience-10','challenges-and-resilience','A time you maintained performance under pressure.'),
('feedback-and-growth-01','feedback-and-growth','Feedback that was difficult to hear.'),
('feedback-and-growth-02','feedback-and-growth','Feedback that changed your behaviour.'),
('feedback-and-growth-03','feedback-and-growth','A time you gave constructive feedback.'),
('feedback-and-growth-04','feedback-and-growth','A time you disagreed with feedback.'),
('feedback-and-growth-05','feedback-and-growth','A skill you deliberately improved.'),
('feedback-and-growth-06','feedback-and-growth','A time you recognised a personal weakness.'),
('feedback-and-growth-07','feedback-and-growth','A time you changed your approach after reflection.'),
('feedback-and-growth-08','feedback-and-growth','A time you learnt from someone less experienced than you.'),
('feedback-and-growth-09','feedback-and-growth','A time you made a mistake and changed a system or habit.'),
('responsibility-and-integrity-01','responsibility-and-integrity','A time you admitted an error.'),
('responsibility-and-integrity-02','responsibility-and-integrity','A time you kept a difficult commitment.'),
('responsibility-and-integrity-03','responsibility-and-integrity','A time you had to choose between convenience and doing the right thing.'),
('responsibility-and-integrity-04','responsibility-and-integrity','A time you stood up for someone else.'),
('responsibility-and-integrity-05','responsibility-and-integrity','A time you challenged dishonest or inappropriate behaviour.'),
('responsibility-and-integrity-06','responsibility-and-integrity','A time you handled confidential information.'),
('responsibility-and-integrity-07','responsibility-and-integrity','A time you had to act without complete information.'),
('responsibility-and-integrity-08','responsibility-and-integrity','A time you were trusted with an important responsibility.'),
('responsibility-and-integrity-09','responsibility-and-integrity','A time you had to set a boundary.'),
('diversity-and-cultural-humility-01','diversity-and-cultural-humility','A time you worked with someone whose life experience differed from yours.'),
('diversity-and-cultural-humility-02','diversity-and-cultural-humility','A time you became aware of your own bias or assumption.'),
('diversity-and-cultural-humility-03','diversity-and-cultural-humility','A time you learnt from another culture or community.'),
('diversity-and-cultural-humility-04','diversity-and-cultural-humility','A time you witnessed exclusion or discrimination.'),
('diversity-and-cultural-humility-05','diversity-and-cultural-humility','A time you helped create a more inclusive environment.'),
('diversity-and-cultural-humility-06','diversity-and-cultural-humility','A time you had to respect a viewpoint you did not share.'),
('diversity-and-cultural-humility-07','diversity-and-cultural-humility','A time you realised that “treating everyone the same” was not enough.'),
('diversity-and-cultural-humility-08','diversity-and-cultural-humility','A time you sought guidance because you lacked cultural knowledge.'),
('patient-facing-or-caring-experiences-01','patient-facing-or-caring-experiences','A time you worked with patients, clients, children, older adults or people with disability.'),
('patient-facing-or-caring-experiences-02','patient-facing-or-caring-experiences','A time you observed healthcare professionals.'),
('patient-facing-or-caring-experiences-03','patient-facing-or-caring-experiences','A time you supported a family member or friend who was unwell.'),
('patient-facing-or-caring-experiences-04','patient-facing-or-caring-experiences','A time you saw how illness affected someone’s daily life.'),
('patient-facing-or-caring-experiences-05','patient-facing-or-caring-experiences','A time you noticed the importance of dignity or privacy.'),
('patient-facing-or-caring-experiences-06','patient-facing-or-caring-experiences','A time you saw excellent or poor communication in healthcare.'),
('patient-facing-or-caring-experiences-07','patient-facing-or-caring-experiences','A time you observed teamwork in a care setting.'),
('patient-facing-or-caring-experiences-08','patient-facing-or-caring-experiences','A time you learnt that the person’s priorities differed from the professional’s priorities.'),
('academic-work-and-research-experiences-01','academic-work-and-research-experiences','A time you investigated a question deeply.'),
('academic-work-and-research-experiences-02','academic-work-and-research-experiences','A time you evaluated whether information was reliable.'),
('academic-work-and-research-experiences-03','academic-work-and-research-experiences','A time you worked on a research or data project.'),
('academic-work-and-research-experiences-04','academic-work-and-research-experiences','A time you balanced study with other commitments.'),
('academic-work-and-research-experiences-05','academic-work-and-research-experiences','A time you worked in a demanding job.'),
('academic-work-and-research-experiences-06','academic-work-and-research-experiences','A time you dealt with an upset customer, client or colleague.'),
('academic-work-and-research-experiences-07','academic-work-and-research-experiences','A time you learnt a new skill quickly.'),
('academic-work-and-research-experiences-08','academic-work-and-research-experiences','A time you improved a process at work or university.'),
('academic-work-and-research-experiences-09','academic-work-and-research-experiences','A time you worked with evidence that was incomplete or conflicting.'),
('advocacy-and-social-responsibility-01','advocacy-and-social-responsibility','A time you advocated for yourself.'),
('advocacy-and-social-responsibility-02','advocacy-and-social-responsibility','A time you advocated for someone else.'),
('advocacy-and-social-responsibility-03','advocacy-and-social-responsibility','A time you identified an unfair barrier.'),
('advocacy-and-social-responsibility-04','advocacy-and-social-responsibility','A time you helped someone access information or support.'),
('advocacy-and-social-responsibility-05','advocacy-and-social-responsibility','A time you became aware of a health or social issue.'),
('advocacy-and-social-responsibility-06','advocacy-and-social-responsibility','A time you participated in environmental or public-health action.'),
('advocacy-and-social-responsibility-07','advocacy-and-social-responsibility','A time you had to balance individual needs with group needs.'),
('advocacy-and-social-responsibility-08','advocacy-and-social-responsibility','A time you helped make a decision about limited resources.');
alter table public.interview_stories add column prompt_id text references public.interview_story_prompts(id);
create index interview_stories_owner_prompt_idx on public.interview_stories(user_id,prompt_id) where prompt_id is not null;
grant insert(prompt_id),update(prompt_id) on public.interview_stories to authenticated;
-- Partial answers can be saved and resumed; existing completed stories are unchanged.
alter table public.interview_stories drop constraint interview_stories_context_check,
 drop constraint interview_stories_actions_check, drop constraint interview_stories_reflection_check;
alter table public.interview_stories add constraint interview_stories_context_check check(char_length(btrim(context))<=2000),
 add constraint interview_stories_actions_check check(char_length(btrim(actions))<=2000),
 add constraint interview_stories_reflection_check check(char_length(btrim(reflection))<=2000),
 add constraint interview_stories_has_content check(char_length(btrim(context))+char_length(btrim(actions))+char_length(btrim(reflection))>0);
commit;
