import { mmiSource } from '../../src/lib/interviews/mmi-evidence'
import { makeMMIFeedback,type MMISpecification } from '../../src/lib/interviews/mmi-feedback'
export const fixtureStation={format:'mmi',station_id:'reflection',title:'Reflection on teamwork',preparation:'Reflect on a disagreement in a group project.',questions:['What did you do and learn?'],evidence_scope:{completeness:'complete',primary_task_coverage:'full'}}
export const fixtureTranscript='T1 Interviewer: What did you learn?\nT2 Candidate: I had assumed my instructions were clear. I would now ask the other person to explain the plan back in their own words so we could find any differences before starting.'
export const fixtureSpec:MMISpecification={task:'Explain own contribution and learning from a disagreement.',role:'Prospective student',basis:'supplied',primary_domains:[{key:'insight_reflection',reason:'The question explicitly requests learning from the experience.'}],essential_expectations:['Explain own action and resulting learning.'],optional_enrichment:['How to check whether the changed approach helps.'],acceptable_approaches:['Any specific, defensible reflection on own role.'],interaction_conditions:'Short complete reflection task; no timing supplied.',limitations:[]}
export function mmiFixture(score:number|null=5){
 const source=mmiSource(fixtureStation,fixtureTranscript)
 return makeMMIFeedback('reflection',source,fixtureSpec,{domains:[{key:'insight_reflection',status:score===null?'insufficient_evidence':'scored',score,evidence:score===null?[]:[{kind:'quote',speaker:'candidate',text:'I had assumed my instructions were clear.',references:['T2']}],rationale:score===null?'The primary reflection is not established in this supplied material.':'Connects a personal assumption to a specific changed behaviour; checking whether the change helps is less developed.',improvement:score===null?'':'Explain how you would know the other person can follow the agreed plan.',needed_evidence:score===null?'The candidate’s account of their contribution and learning.':''}],global:{status:score===null?'insufficient_evidence':'scored',score,reason:score===null?'The primary task cannot be judged from the available evidence.':'The complete short task shows a specific reflection and relevant change.'},strengths:score===null?[]:[{domain:'insight_reflection',text:'Identifies a personal assumption and a specific change in how to check understanding.',references:['T2']}],priorities:score===null?[]:[{domain:'insight_reflection',text:'Explain how to check that the agreed plan is now understood.',references:['T2']}],concerns:[],closing:{verdict:score===null?'The available evidence does not support a station judgement.':'This is a specific and relevant reflection on your own contribution.',successful_improvement:score===null?'The missing response is needed before an improvement can be identified.':'A stronger answer would explain how you would check that the revised approach resolves the misunderstanding.'}})
}
