import {wholePanelSource,type PanelMember} from '../../src/lib/interviews/panel-source'
import {blankWholePanelFeedback,type PanelPlan,type PanelAssessment} from '../../src/lib/interviews/panel-feedback'
export const panelOwner='00000000-0000-4000-8000-000000000001',panelAdmin='00000000-0000-4000-8000-000000000002',panelSession='20000000-0000-4000-8000-000000000001'
export function panelMembers(batch=1):PanelMember[]{return Array.from({length:10},(_,index)=>({id:`10000000-0000-4000-8000-${String(batch*100+index).padStart(12,'0')}`,user_id:panelOwner,format:'panel',station_title:index===0?'Motivation for medicine':'Experience and reflection',station_snapshot:{format:'panel',preparation:'Discuss your own experience.',questions:[index===0?'Why medicine?':'What did you do and learn?'],timing:{response_seconds:120},mock_session:{id:panelSession,mode:'full',total:10,index}},questions:[index===0?'Why medicine?':'What did you do and learn?'],transcript:index===0?'Candidate: I enjoy understanding how illness affects people and want to learn to make treatment decisions with patients.':'Candidate: At the community lunch I asked volunteers which tasks they preferred. When the rota failed, I found cover and realised I needed to check availability before assigning shifts.',transcription_status:'ready',duration_seconds:120,video_deleted_at:null,upload_status:'ready'}))}
export function panelFixture(members=panelMembers()):PanelAssessment{
 const source=wholePanelSource(members,panelSession,panelOwner)
 const plan:PanelPlan={basis:'provisional',purpose:'Motivation and reflection across the supplied questions.',primary_domains:['motivation_medicine','reflection_learning'],tasks:source.sequences.map((s,i)=>({sequence:s.id,primary:true,domains:i===0?['motivation_medicine','communication_relevance']:['reflection_learning','personal_evidence','communication_relevance'],essential:i===0?'Explain an informed interest in medicine.':'Explain your action and what you learned.',optional:'Further relevant detail.'})),limitation:'Synthetic workflow fixture; no tutor reference rating.'}
 const feedback=blankWholePanelFeedback(source,plan)
 feedback.question_coverage.forEach(q=>{q.coverage='addressed';q.observation='A relevant response is available.'})
 feedback.domains.forEach(d=>{if(d.state!=='not_elicited'){d.state='scored';d.score=5;d.evidence=[source.sequences[d.key==='motivation_medicine'?0:1].references.find(r=>r.speaker==='candidate')!.id];d.why='You explained your reasoning with a relevant example.';d.improvement='Explain how you would check the outcome of your next action.'}else d.why='This question set does not elicit this domain.'})
 feedback.global_rating={score:5,band:'Good',basis:'The supplied answers meet the primary tasks; more detail about checking outcomes would strengthen them.'};feedback.strengths=['You connected your own action to what you learned.'];feedback.priorities=['Explain how you would know whether your change helped.'];feedback.closing_paragraph='You gave a thoughtful account of your experience. Explaining how you would check the effect of your changes would make your reflection more useful.'
 return {mode:'panel_complete',source,plan,feedback}
}
